### ISSUE TITLE
Changelog for the last n commits

### ISSUE THREAD

**Issue by corentin-wedge** [orhun/git-cliff#102]
It could be nice to specify a variable "n" in the cliff.toml used to limit the size of the changelog.

Select the last n commits, If the n commits is inside a tag, includes all the commits of the tag.

thanks 🙂

**Comment by FlrnFrmm** [comment]
Attempt to add the demanded feature with #116.

To be honest, I was not 100% sure what is meant with

> If the n commits is inside a tag, includes all the commits of the tag.

Wouldn't that be confusing? 

Let's assume I limit to the last 15 commits, but the last 2 of the commits are part of a tag with 10 commits.
So I would get 25 commits as a result? 

The implementation in the PR strictly limits the number of commits in the changelog.

**Comment by corentin-wedge** [comment]
Yeah this was confusing my bad, and you're right, this is better to stop at the limit.

**Comment by orhun** [comment]
Implemented in #116
