### ISSUE TITLE
Support ARM64 builds for M1 macs

### ISSUE THREAD

**Issue by joberget** [orhun/git-cliff#103]
**Describe the solution you'd like**
Builds supporting M1 ARM64 Architecture

**Comment by joberget** [comment]
Oh I found this through brew, no need to have this opened then. :)

**Comment by h3adache** [comment]
commenting on a closed issue but just wanted to mention that tool sharing using asdf/mise is quite popular for development teams. 

Was looking to switch to using `git-cliff` for changelog generation but ran into this when trying to `mise install git-cliff` as it uses https://github.com/jylenhof/asdf-git-cliff which tries to pull the releases based on arch.

**Comment by orhun** [comment]
@h3adache it is probably better to report it to the packager? Is there anything that I can do from the builds side?

**Comment by h3adache** [comment]
Thanks for the quick response @orhun! It's an issue that can actually be solved by either publishing a release asset for arm64 darwin or fixing the packager to accept ARCH overrides as you mentioned.

**Comment by h3adache** [comment]
Yes but `aarch64` isn't what is returned by `uname` which is what most tool use when checking arch.

https://github.com/h3adache/asdf-git-cliff/blob/main/lib/utils.bash#L35-L43

**Comment by orhun** [comment]
You can see the naming convention here: <https://github.com/orhun/git-cliff/blob/main/.github/workflows/cd.yml#L36-L131>

Changing that would break the other build systems so I suggest fixing that at downstream.
