### ISSUE TITLE
Header date sometimes off by multiple days

### ISSUE THREAD

**Issue by michewl** [orhun/git-cliff#107]
**Describe the bug**

The date in the header created for `--tag` with a config like this `{{ timestamp | date(format="%Y-%m-%d") }}` (from the [detailed.toml](https://github.com/orhun/git-cliff/blob/main/examples/detailed.toml#L13)) is sometimes off by multiple days.

Adding a timezone or locale does not change the generated date. Using `%F` as format also generates the wrong date.

It does not seem to be the case for header dates of previous versions, so I believe it is related to the `--tag` flag.

Timestamp value from context: `1661348531`
This should generate `2022-08-29`, but will generate `2022-08-24`

**To Reproduce**

1. Generate a changelog that has above template in the config with `--tag 1.2.3` for the "unreleased changes".

The full command I use is: `git cliff --config .config/cliff.toml --output CHANGELOG.md --tag 1.2.3`

**Expected behavior**

The date should be the correct one for the timestamp in the context (`--context`).

**System (please complete the following information):**
 
- OS Information: `Pop!_OS 22.04 LTS Linux 5.19.0-76051900-generic x86_64 GNU/Linux`
- Git Cliff Version: `git-cliff 0.9.0`
- Git Version: `git version 2.34.1`

**Comment by michewl** [comment]
I think I am mistaken with the timestamp example, but the time still seems to be off when using the `--tag` flag (`git-cliff 0.9.2`).

This might be the expected behavior, and I am mistaken for what the timestamp does. I would expect when using `--tag`, that it uses "now".

I think however, that it uses the date from the latest commit?
Can this be configured to use `now` in case of `--tag`, but not for the other regular git tags that already exist?

**Comment by orhun** [comment]
> I think I am mistaken with the timestamp example, but the time still seems to be off when using the `--tag` flag (`git-cliff 0.9.2`).
> 
> This might be the expected behavior, and I am mistaken for what the timestamp does. I would expect when using `--tag`, that it uses "now".
> 
> I think however, that it uses the date from the latest commit? Can this be configured to use `now` in case of `--tag`, but not for the other regular git tags that already exist?

Good point! I implemented it in e2cd07bcc92a6bdd011bbbb34843f22e6c4da271

`--tag` uses `now` from now on.
