### ISSUE TITLE
Specify a subpath to build the changelog

### ISSUE THREAD

**Issue by pgmillon** [orhun/git-cliff#11]
Hi,
In the context of a mono-repo, is it possible to specify the repository subpath to build the changelog from ?

Something like git cliff -- subpath/

Thanks.

**Comment by orhun** [comment]
Hello,

You can do `git cliff --repository subpath/` and it will use the git repository in `subpath/`.

If that's not what you mean, please elaborate.

**Comment by pgmillon** [comment]
Hi,
Thanks for the quick answer.
So, I have multiple projects in a mono-repo and I'd like to get the changelog of only one of these projects:
```
git-repo-root
├── project1
│  └── CHANGELOG.md
└── project2
    └── CHANGELOG.md
```
For now, I usually do `conventional-changelog --commit-path=project1 -t releases/project1/v -o project1/CHANGELOG.md`
I think something similar in git-cliff is required to be useful in monorepos :)

Regards,

**Comment by orhun** [comment]
> So, I have multiple projects in a mono-repo and I'd like to get the changelog of only one of these projects:
> 
> ```
> git-repo-root
> ├── project1
> │  └── CHANGELOG.md
> └── project2
>     └── CHANGELOG.md
> ```

I see. Have you tried `--repository` option? (e.g. `git cliff --repository project1`)

**Comment by pgmillon** [comment]
Yes, but I have an error:
```
$ git cliff --repository foundry-extensible-plugin
 ERROR git_cliff > Git error: `could not find repository from 'foundry-extensible-plugin'; class=Repository (6); code=NotFound (-3)`
```

**Comment by orhun** [comment]
I think I finally get it 😃 

0bb7c91 -> adds `--commit-path <PATH>` argument for generating a changelog scoped to a specific directory

e.g.

```sh
git cliff --commit-path git-cliff-core/ -o git-cliff-core/CHANGELOG.md
```

This argument will be available with the next release. In the meantime feel free to test it out and report bugs if any 🐻

**Comment by orhun** [comment]
`v0.3.0` is released.
