### ISSUE TITLE
Package for debian/ubuntu

### ISSUE THREAD

**Issue by fago** [orhun/git-cliff#113]
**Is your feature request related to a problem? Please describe.**
Install git-cliff for debian/ubuntu is not necessarily quick. It would be convenient if a debian package could be provided.

**Describe the solution you'd like**
Provide an AMD64 debian package that simply packages up the gnu-linux binary.

**Comment by orhun** [comment]
Hi!

I updated the release workflow to publish Debian packages (built via [cargo-deb](https://github.com/kornelski/cargo-deb)).

See the related commit: efd827f59f8394dd894ebd35a5d630ff558a3ebe

Thanks for the suggestion! 🐻
