### ISSUE TITLE
Add author/contributor name to the changelogs

### ISSUE THREAD

**Issue by pyrito** [orhun/git-cliff#119]
**Is your feature request related to a problem? Please describe.**
Currently git-cliff does not parse out the author names and save them at the end of the changelog.

**Describe the solution you'd like**
Add an option to write out contributor names at the end of the changelog.

**Comment by pyrito** [comment]
@orhun this is something I could probably take on with some guidance code wise. I think we just need to parse out the contributor names and maintain them in a set.

**Comment by gautamprikshit1** [comment]
https://github.com/orhun/git-cliff/blob/77731ec7aeb279b5b7a49b5f7d17cc51009afca2/git-cliff-core/src/commit.rs#L118

I think this can be helpful

**Comment by PSeitz** [comment]
This can already be accessed via the template, e.g.

```
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | upper_first }}
    {% for commit in commits %}
        - {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message | upper_first }}\
        Author: {{ commit.author.name }}
    {% endfor %}
{% endfor %}\n
```

**Comment by anas-elgarhy** [comment]
@orhun I think that I can try to implement this if you don't mind

**Comment by orhun** [comment]
You can now achieve this with the [GitHub integration](https://git-cliff.org/docs/integration/github).
