### ISSUE TITLE
Update clap to v4

### ISSUE THREAD

**Issue by orhun** [orhun/git-cliff#125]
**Is your feature request related to a problem? Please describe.**

```sh
$ cargo outdated
git-cliff
================
Name           Project  Compat  Latest  Kind    Platform
----           -------  ------  ------  ----    --------
clap           3.2.23   ---     4.0.26  Normal  ---
clap_complete  3.2.5    ---     4.0.5   Normal  ---
clap_mangen    0.1.11   ---     0.2.4   Normal  ---
```

**Describe the solution you'd like**
Update `clap`, `clap_complete` and `clap_mangen` to the latest version.

**Describe alternatives you've considered**
None.

**Additional context**
Changelog: https://github.com/clap-rs/clap/blob/master/CHANGELOG.md#400---2022-09-28

**Comment by DhwanishShah** [comment]
I want to work on this issue. Can you please assign me this issue?

**Comment by orhun** [comment]
Assigned you to the issue @DhwanishShah

**Comment by orhun** [comment]
@DhwanishShah is there a time frame that you can give it to me for closing this issue?

**Comment by Jehan-h20220012** [comment]
I want to close this issue.
@orhun  Please guide me for the same and tell me where and how to make changes so that I can raise a PR as soon as possible

**Comment by Jehan-h20220012** [comment]
@orhun If i update the version in "Cargo.lock", should it suffice?

**Comment by orhun** [comment]
First, you need to update `Cargo.toml` for using the latest version of `clap`. Then you should update `git-cliff/src/args.rs` to accommodate the changes. You should read the clap changelog for making the appropriate updates on the arguments.

**Comment by Jehan-h20220012** [comment]
Okay, I will do the needy

**Comment by Jehan-h20220012** [comment]
I am waiting for approval of my PR to merge it and close the issue

**Comment by Jehan-h20220012** [comment]
@orhun please approve my PR and merge

**Comment by lbowenwest** [comment]
Hi @orhun, looks like there's been a few attempts at this, am I alright to have a go at it?
