### ISSUE TITLE
Make `--date-order` default

### ISSUE THREAD

**Issue by orhun** [orhun/git-cliff#126]
**Is your feature request related to a problem? Please describe.**
Making topological order default in #58 caused more problems than expected, especially for `--latest` and `--current` flags.

**Describe the solution you'd like**
Make `--date-order` default again.

**Describe alternatives you've considered**
\-

**Additional context**
See #124

**Comment by DhwanishShah** [comment]
I want to work on this issue. Can you please assign me this issue? It's my college assignment to solve any issue on GitHub.@orhun @Groxx

**Comment by orhun** [comment]
You got it!

**Comment by orhun** [comment]
This is free for grab now.
