### ISSUE TITLE
What is the difference between the msvc and gnu binaries?

### ISSUE THREAD

**Issue by Zliced13** [orhun/git-cliff#127]
The question is in the title ⤴

**Comment by orhun** [comment]
`msvc` means `git-cliff` is compiled for [Windows](https://rust-lang.github.io/rustup/installation/windows.html#windows). GNU means `git-cliff` is compiled using GNU C compiler as `x86_64-linux-gnu-gcc` target.

**Comment by Zliced13** [comment]
@orhun That makes more sense, thank you for taking the time to explain it to me. Have a great rest of your day.
