### ISSUE TITLE
Is it possible to generate single changelog for multiple git projects

### ISSUE THREAD

**Issue by darkLord19** [orhun/git-cliff#13]

**Comment by orhun** [comment]
Hello, it is not possible for now. It can be implemented but can you give some details about your use-case? I'm wondering when such thing can be useful.

**Comment by darkLord19** [comment]
@orhun in microservices environments or environment where one release consists of multiple separate components deployments

**Comment by orhun** [comment]
I see. The problem is `git-cliff` currently _parses_ the commit history and splits the commits into groups by tags. So in the case of multiple git histories, it should join the histories and group the commits somehow, if that's what you meant by "multiple git projects".

e.g.

```
git cliff --repository <repo_path1> <repo_path2>
```

Would that be sufficient for your use-case?

**Comment by alerque** [comment]
@darkLord19 Are you using a monorepo for multiple service projects or multiple repositories? Your question about "projects" and "components" doesn't make it clear how you are handling these in relation to repositories.

**Comment by orhun** [comment]
@darkLord19 can you clarify @alerque's question before I proceed with the implementation?

**Comment by darkLord19** [comment]
@orhun `git cliff --repository <repo_path1> <repo_path2>` ye this is exactly what I mean. I have multiple repos and it should join commits

**Comment by ZhukovWang** [comment]
Hello, I try this command `git cliff --repository <repo_path1> <repo_path2> -l --output changlog.md`, but this only outputs changelog of `repo_path1`, doesn't contain `repo_path2`.

And I read the code, seems the type of `repository` is not right? [code line is here](https://github.com/orhun/git-cliff/blob/261ee4f146ac7d68353dd052c62a510aadebfad4/git-cliff/src/args.rs#L48). It should be `Option<Vec<PathBuf>>`, not `Option<PathBuf>`, like `include_path`.

**Comment by orhun** [comment]
I implemented this in 8b17a1f02619027bebc5df1a8938aaf76adcd631 and will be available with the next release.
