### ISSUE TITLE
Incorrect footers values

### ISSUE THREAD

**Issue by rosen-kanev** [orhun/git-cliff#130]
**Describe the bug**
It seems that parsing of the footer trailers produces incorrect values with valid git trailers.

**To Reproduce**
1. Create a commit with the message
```
fix(example): fix keepachangelog config example

Fixes: #123, #124, #125
```
2. Update `cliff.toml` config with this `body` to output the footers:
```toml
body = """
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | upper_first }}
    {% for commit in commits %}
        - {{ commit.message | upper_first }} ({{ commit.footers | map(attribute="value") | join(sep=", ") }})\
    {% endfor %}
{% endfor %}\n
"""
```
3. `git-cliff` outputs
```md
### Bug Fixes

- Fix keepachangelog config example (, , 125)
```

**Expected behavior**
```md
### Bug Fixes

- Fix keepachangelog config example (#123, #124, #125)
```

**Screenshots/Logs**
N/A

**System (please complete the following information):**
 - OS Information: x86_64-apple-darwin (macOS 16.2)
 - Project Version: 0.10.0

**Additional context**
I'm using [git trailers](https://git-scm.com/docs/git-interpret-trailers) to add the related issues in the commit message. According to its documentation the trailer value may contain whitespace and as a sanity check:
```sh
echo "fix(example): fix keepachangelog config example\n\nFixes: #123, #124, #125" | git interpret-trailers --parse # Fixes: #123, #124, #125
```
When I use git-cliff to generate a changelog the parsing produces unexpected results.
<details><summary>JSON output</summary>
<pre>
[
  {
    "token": "Fixes",
    "separator": ":",
    "value": "",
    "breaking": false
  },
  {
    "token": "#123,",
    "separator": " #",
    "value": "",
    "breaking": false
  },
  {
    "token": "#124,",
    "separator": " #",
    "value": "125",
    "breaking": false
  }
]
</pre>
</details>

Interestingly, using a separate trailer for each related issue like this commit message:
```
fix(example): fix keepachangelog config example

Fixes: #123
Fixes: #124
Fixes: #125
```
git-cliff correctly outputs:
```md
### Bug Fixes

- Fix keepachangelog config example (#123, #124, #125)
```
`git log` gets too noisy when there are many related issues so I'd rather have them in a comma-separated list.

**Comment by orhun** [comment]
Hi! Thanks for the detailed issue 🐻

Unfortunately this is not possible since such commits are not conventional and cannot be parsed.
[`Footer`](https://docs.rs/git-conventional/latest/git_conventional/struct.Footer.html) object only contains `token`, `separator` and `value` since you normally have `<token><separator><value>` as your footer. See the [specification](https://www.conventionalcommits.org) and [footers section](https://github.com/orhun/git-cliff#footers) in README.md.

> using a separate trailer for each related issue

Yes, this is the correct usage of conventional footers.

Feel free to ask in [git-conventional](https://github.com/crate-ci/git-conventional) to double-check since `git-cliff` only reflects what it gets from the parser.

**Comment by rosen-kanev** [comment]
`git-conventional` fixed the footer parsing issue https://github.com/crate-ci/git-conventional/issues/34 and it seems like they released a new version with the patch. Any chance that `git-cliff` cuts a new release as well? Oh btw, congrats on the Dec 25 v1 release 🎉

**Comment by orhun** [comment]
Thank you! I pushed c74fcc294b7bd2cd9b6740577ee337504f5d8a60 and it will be available with the next release.
