### ISSUE TITLE
Use GitHub username?

### ISSUE THREAD

**Issue by max-sixty** [orhun/git-cliff#132]
**Is your feature request related to a problem? Please describe.**

This might be asking too much, but currently the changes in https://github.com/orhun/git-cliff/issues/100 use the author in the git commit, which is frequently an unfriendly `noreply` email; e.g.:

```
- Sync our main example across readme & book (#1112)- Maximilian Roos <5635139+max-sixty@users.noreply.github.com> 2022-11-05

- Update ci badge link (#124)- Kyle Wigley <kwigley44@gmail.com> 2022-02-24
```

**Describe the solution you'd like**

We'd want the GitHub usernames — I imagine this would be highly preferable for most projects...

**Describe alternatives you've considered**

Ironically the unfriendly `5635139+max-sixty@users.noreply.github.com` could be parsed into @max-sixty. But where they're not masked, possibly it would be necessary to query GitHub for them?

Ref https://github.com/PRQL/prql/issues/736

**Comment by orhun** [comment]
Hello!

Unfortunately I won't be adding specific GitHub-related features to `git-cliff`. I briefly mentioned this in #112:

> It is always good to refrain from adding code-hosting related things to `git-cliff` since it is not specifically designed to work with e.g. GitHub, GitLab, etc. These remote URLs might change any time depending on which platform you are using. `git-cliff` should only integrate well with `git` and it should be configurable based on user liking.

I suggest you update your committer details accordingly to your GitHub account:

```sh
git config --global user.name "John Doe"
git config --global user.email "john@doe.org"
```

> But where they're not masked, possibly it would be necessary to query GitHub for them?

Yes, that's why it will complicate things further.

Thank you for the suggestion! 🐻

**Comment by max-sixty** [comment]
Thanks @orhun ; that makes sense — both the additional complication and the GH specificity.

FWIW if you can think of another way of achieving something like this; e.g. a config file with a lookup from email to handle which changelogs can then use, that would be quite nice. If I do a quick survey of changelogs, almost all use GH handles, and while I'm no fan of hegemony, GH do have one in open-source projects...

Thanks again for the excellent tool!

**Comment by tqwewe** [comment]
I'd love to see this! Something where it looks up the username from emails would be amazing.

**Comment by orhun** [comment]
I doubled down on this and created a PR for GitHub integration: #363

**Comment by orhun** [comment]
You can now achieve this with the [GitHub integration](https://git-cliff.org/docs/integration/github).
