### ISSUE TITLE
How to regex replace strings?

### ISSUE THREAD

**Issue by faustbrian** [orhun/git-cliff#14]
Hey, great project but was wondering if it is possible to perform regex replacements in values like commit messages.

Something like `{{ commit.message | replace(from="#(\d+)", to="") }}` to turn `Update dependencies (#57)` into `Update dependencies`

**Comment by orhun** [comment]
[Tera](https://github.com/Keats/tera) already has a built-in filter called [`replace`](https://tera.netlify.app/docs/#replace) but it doesn't support regex. There's already a tracking issue: [Keats/tera#421](https://github.com/Keats/tera/issues/421)

**Comment by orhun** [comment]
Closing due to being Tera related.
