### ISSUE TITLE
Output only merge commits into the default branch

### ISSUE THREAD

**Issue by hituzi-no-sippo** [orhun/git-cliff#143]
## Overview

I want to output only merge commits into the default branch (main).
I've thought of my own solution, but is there a better one out there?

## Description

**Example Repository**
[hituzi-no-sippo/merge-commit-only-git-cliff](https://github.com/hituzi-no-sippo/merge-commit-only-git-cliff)

For the following git log

<details><summary>git log</summary>

`git log --graph --pretty="%H%n%n%B" HEAD^`

```console
*   f24c87f2ec023cb37b25957f0c678ba50d3f7cf2
|\
| | fix: donut merge commit
| |
| | Merge branch 'donut'
| |
| * cf727a7ca7ab6ad7f6f39739cb24f5ddb7a7508f
|/
|   fix: donut
|
*   2c211a56a0d80f84b7fe89b008f780bc56b20938
|\
| | feat: banana merge commit
| |
| | Merge branch 'banana'
| |
| *   0838fcb8336885399a6f9a3cd51de4751660d4f1
| |\
| | | perf: cacao merge commit
| | |
| | | Merge branch 'banan-cacao' into banana
| | |
| | * c32be0364e58a5cb6c9f41a7f642fc480d60ae26
| |/
| |   perf: cacao
| |
| * 1c744d48aeb64ab0b6d20abc6d09c4d2c531f498
|/
|   feat: banana
|
*   93ad4a4b7f8c25ecadede3b35c58fe85178ffe4d
|\
| | chore: apple merge commit
| |
| | Merge branch 'apple'
| |
| * 609b30e1e2adb2353205725f92a8bbd2a99a4b3a
|/
|   chore: apple
|
* c7bfa61551d821feb0cc8f71542b64a8750c9cec

  Initial commit
```

</details>

I want to output only the next commit in CHANGELOG.

<details><summary>git log</summary>

`git log --graph --pretty="%H%n%n%B"`

```console
* f24c87f2ec023cb37b25957f0c678ba50d3f7cf2
|
| fix: donut merge commit
|
| Merge branch 'donut'
|
* 2c211a56a0d80f84b7fe89b008f780bc56b20938
|
| feat: banana merge commit
|
| Merge branch 'banana'
|
* 93ad4a4b7f8c25ecadede3b35c58fe85178ffe4d

  chore: apple merge commit

  Merge branch 'apple'
```

</details>

### CHANGELOG

**[Expected](https://github.com/hituzi-no-sippo/merge-commit-only-git-cliff/blob/main/merge-commit-only.md)**

<details>

```markdown
# Changelog

All notable changes to this project will be documented in this file.

## [unreleased]

### Bug Fixes

- Donut merge commit

### Features

- Banana merge commit

### Miscellaneous Tasks

- Apple merge commit

<!-- generated by git-cliff -->
```

</details>

**[default config(`git-cliff --init`)](https://github.com/hituzi-no-sippo/merge-commit-only-git-cliff/blob/main/default.md)**

<details>

```markdown
# Changelog

All notable changes to this project will be documented in this file.

## [unreleased]

### Bug Fixes

- Donut
- Donut merge commit

### Features

- Banana
- Banana merge commit

### Miscellaneous Tasks

- Apple
- Apple merge commit

### Performance

- Cacao
- Cacao merge commit

<!-- generated by git-cliff -->
```

</details>

**diff**

[hituzi-no-sippo/merge-commit-only-git-cliff/CHANGELOG.diff](https://github.com/hituzi-no-sippo/merge-commit-only-git-cliff/blob/main/CHANGELOG.diff)

```diff
--- default.md	2023-02-05 19:59:53.498790000 +0900
+++ merge-commit-only.md	2023-02-05 19:59:58.658790000 +0900
@@ -6,22 +6,14 @@
 
 ### Bug Fixes
 
-- Donut
 - Donut merge commit
 
 ### Features
 
-- Banana
 - Banana merge commit
 
 ### Miscellaneous Tasks
 
-- Apple
 - Apple merge commit
 
-### Performance
-
-- Cacao
-- Cacao merge commit
-
 <!-- generated by git-cliff -->
```

## Why skip normal commit

 A merge commit contains a portion of content that is not a merge commit.

##  I solution considered

- Add `.*\n+Merge branch '.*'\n$` to message in `commit_parsers`
- Change `filter_commits`  to `true`

### Diff

[hituzi-no-sippo/merge-commit-only-git-cliff/config.diff](https://github.com/hituzi-no-sippo/merge-commit-only-git-cliff/blob/main/config.diff)

```diff
--- cliff.toml	2023-02-05 19:57:23.288790000 +0900
+++ merge-commit-only.toml	2023-02-05 19:57:41.898790000 +0900
@@ -42,21 +42,21 @@
 ]
 # regex for parsing and grouping commits
 commit_parsers = [
-    { message = "^feat", group = "Features"},
-    { message = "^fix", group = "Bug Fixes"},
-    { message = "^doc", group = "Documentation"},
-    { message = "^perf", group = "Performance"},
-    { message = "^refactor", group = "Refactor"},
-    { message = "^style", group = "Styling"},
-    { message = "^test", group = "Testing"},
-    { message = "^chore\\(release\\): prepare for", skip = true},
-    { message = "^chore", group = "Miscellaneous Tasks"},
-    { body = ".*security", group = "Security"},
+    { message = "^feat.*\n+Merge branch '.*'\n$", group = "Features"},
+    { message = "^fix.*\n+Merge branch '.*'\n$", group = "Bug Fixes"},
+    { message = "^doc.*\n+Merge branch '.*'\n$", group = "Documentation"},
+    { message = "^perf.*\n+Merge branch '.*'\n$", group = "Performance"},
+    { message = "^refactor.*\n+Merge branch '.*'\n$", group = "Refactor"},
+    { message = "^style.*\n+Merge branch '.*'\n$", group = "Styling"},
+    { message = "^test.*\n+Merge branch '.*'\n$", group = "Testing"},
+    { message = "^chore\\(release\\): prepare for.*\n+Merge branch '.*'\n$", skip = true},
+    { message = "^chore.*\n+Merge branch '.*'\n$", group = "Miscellaneous Tasks"},
+    { body = ".*security.*\n+Merge branch '.*'\n$", group = "Security"},
 ]
 # protect breaking changes from being skipped due to matching a skipping commit_parser
 protect_breaking_commits = false
 # filter out the commits that are not matched by commit parsers
-filter_commits = false
+filter_commits = true
 # glob pattern for matching git tags
 tag_pattern = "v[0-9]*"
 # regex for skipping tags
```

## Additional context

I am wondering if I should feature request to output only merge commits to the default branch.
Because I don't know if many people use this output.

**Comment by orhun** [comment]
Thanks for the detailed report and example repository! 🐻

The solution that you came up with is actually not bad. Of course, it would be easier if there was a flag such as `--only-merge` or something like that. However, as you mentioned, I'm not sure if this is a widely requested feature so I will keep this issue open with "how-to" label in case someone else wants to achieve the same thing.

Note: I might implement this feature if you think it is actually needed but I think it seems a bit unlikely right now. And as always, I'm open to PRs!

**Comment by jonathanj** [comment]
An issue I'm running into is that squashed merge commits (with no extra commits) have exactly the same message in our repo.

```
Merge: 50f760dd0 c1fd59860
Author: Some Person <someone@example.com>
Date:   Wed Sep 13 10:30:36 2023 +0000

    Merge branch 'upgrade-design-system-icons' into 'master'

    feat: Upgrade design-system-icons to 1.47.0

    See merge request org/repo!729

commit c1fd598601ecc78a15ff76fff1f5b1c332c99ce4
Author: Some Person <someone@example.com>

Date:   Wed Sep 13 10:30:34 2023 +0000

    Merge branch 'upgrade-design-system-icons' into 'master'

    feat: Upgrade design-system-icons to 1.47.0

    See merge request org/repo!729
```

(If there is more than one squashed commit, then an additional "Commits: …" part is added to the body, which I can filter by.)

Having the merge commit metadata tracked and accessible in `commit_parsers` would be very useful to me:

```
commit_parsers = [
  { is_merge_commit = true, skip = true },
  # …
]
```

**Comment by orhun** [comment]
After #389 is merged, you can do this in the template to filter out the merge commits (which I think satisfies your use-case):

```jinja2
{% for group, commits in commits | filter(attribute="merge_commit", value=false) %}
```

Also, I think there are a good number of tricks in this issue (such as the use of `unique`) - I'm not sure if you're still around but @jonathanj @hituzi-no-sippo would you be interested in adding those to the documentation (under a new section called Tips / Tricks)?

Then I think we can close this issue.

🐻

**Comment by orhun** [comment]
Tips and tricks are added in https://git-cliff.org/docs/tips-and-tricks

**Comment by paul-uz** [comment]
@orhun where do i add this line in the default config file?

`{% for group, commits in commits | filter(attribute="merge_commit", value=false) %}`

I tried replacing `{% for group, commits in commits | group_by(attribute="group") %}` but i got the following error

> Tried to iterate using key value on variable `commits`, but it isn't an object/map

**Comment by orhun** [comment]
You need to combine both of those filter options like so:

```
{% for group, commits in commits | filter(attribute="merge_commit", value=false) | group_by(attribute="group") %}
```

**Comment by paul-uz** [comment]
@orhun excellent thanks. I would recommend updating the docs to make this clearer 👍

**Comment by orhun** [comment]
Good idea, would you be interested in submitting a PR maybe? 😊
