### ISSUE TITLE
Adding `git-cliff` to PyPI

### ISSUE THREAD

**Issue by radusuciu** [orhun/git-cliff#150]
**Is your feature request related to a problem? Please describe.**
This is similar in scope to the feature described in #133 and implemented in #134. This would make it seamless for Python projects to install and use `git-cliff` and would pair nicely with the newly added support for configuration in `pyproject.toml`. It also fits nicely in the recent [rustification of python tooling trend](https://notes.crmarsh.com/python-tooling-could-be-much-much-faster).

**Describe the solution you'd like**
The approach you described in your [blog post](https://blog.orhun.dev/packaging-rust-for-npm/) for npm can be adapted for PyPI. I think the best approach would be to use [`maturin`](https://github.com/PyO3/maturin#python-packaging-basics). For an example, you can check out [this workflow in the ruff project](https://github.com/charliermarsh/ruff/blob/main/.github/workflows/ruff.yaml).

I'm willing to take a shot at a PR if you're interested in adding this feature. Thanks!

**Comment by orhun** [comment]
Hello @radusuciu! 🐻

I have been already thinking about this but couldn't find the time to properly implement it. The way that you described seems feasible to me and it would be absolutely great to have `git-cliff` on PyPI.

One example project to look at is [typos](https://github.com/crate-ci/typos) which has a [PyPI package](https://pypi.org/project/typos/). It also has a similar [implementation](https://github.com/crate-ci/typos/commit/f2868fa76ee2c0993cf669c1b8d1f3142a31ebbc).

> I'm willing to take a shot at a PR if you're interested in adding this feature. Thanks!

Please do!

**Comment by radusuciu** [comment]
Alright, I'll give it a shot and thank you for sharing `typos` example!

**Comment by orhun** [comment]
Great, I'll look forward to it!

**Comment by orhun** [comment]
Hey @radusuciu, I was wondering if you're still interested. I can assign the issue to you if you're planning to work on it :3

**Comment by radusuciu** [comment]
> Hey @radusuciu, I was wondering if you're still interested. I can assign the issue to you if you're planning to work on it :3

I am still interested but this week is very busy with work/life so I cannot work on it. You can go ahead and assign it to me however. The reason I'd like to have this feature is because I want to use `git-cliff` in more python projects and having it on PyPI makes this way smoother, so I am definitely motivated :)

**Comment by orhun** [comment]
Awesome, just wanted to let you know that the documentation is moved to [docs/](https://github.com/orhun/git-cliff/tree/main/website/docs) and live on https://git-cliff.org

You can simply create `installation/python.md` for updating the documentation 🐻

**Comment by orhun** [comment]
Another interesting thing would be building musl wheels: https://github.com/crate-ci/typos/commit/54042f2124fb174de8f1b07831b6edbe6e423da7
