### ISSUE TITLE
Package for RPM

### ISSUE THREAD

**Issue by orhun** [orhun/git-cliff#159]
**Is your feature request related to a problem? Please describe.**

It would be nice to distribute an [RPM package](https://docs.fedoraproject.org/en-US/fedora/latest/system-administrators-guide/RPM/) as a part of the releases.

**Describe the solution you'd like**

Generate an RPM via [`cargo-generate-rpm`](https://github.com/cat-in-136/cargo-generate-rpm) during continuous deployment and publish it on GitHub releases.

**Describe alternatives you've considered**

None.

**Additional context**

See this example: https://github.com/fujiapple852/trippy/pull/410

**Comment by radusuciu** [comment]
Since I've been digging around in the CD workflow I can take a crack at this if you'd like. The example seems simple enough.

**Comment by orhun** [comment]
Please go ahead @radusuciu!

Btw I'm pretty busy lately so I couldn't check your other PR yet, will get to it soon. Thanks!

**Comment by radusuciu** [comment]
Alright, will be 1-2 weeks before I have a PR for this so if you or anyone beats me to it please go ahead!

Regarding the PyPI PR -- no worries, I've done some testing work and made some fixes. I deleted a few interim updates to reduce the noise for when you have time for final review.

**Comment by orhun** [comment]
I handled this in baf4da80639682628ca4ae538b4555ff1b6262da

Thanks again @radusuciu!
