### ISSUE TITLE
Modify tests to include `docs:` prefix

### ISSUE THREAD

**Issue by beeb** [orhun/git-cliff#164]
**Describe the bug**

~~In the generated config file, the regex that is setup for documentation commits is `^doc`:~~

In the unit tests, the prefix for documentation commit tests is `doc:`.

https://github.com/orhun/git-cliff/blob/5ec4d1f76fa411f64de5ea7d1263dbb87492a94d/config/cliff.toml#L51

https://github.com/orhun/git-cliff/blob/5ec4d1f76fa411f64de5ea7d1263dbb87492a94d/git-cliff-core/src/changelog.rs#L245

This is not in line with [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) which dictates the use of `^docs` (plural).

**To reproduce**

1: `git cliff --init`
2. open `cliff.toml` and check line 14.

**Expected behavior**

Match conventional commis recommendations

**Screenshots / Logs**

N/A

**Software information**

- Project version: 1.2.0

**Comment by orhun** [comment]
It was a decision to simply support `doc: blahblah` format since I saw a couple of projects doing that. But as you said, it is not conventional so it would be feasible to change it. Are you interested in making a PR?

**Comment by beeb** [comment]
I could make a PR yeah, what are the implications, can I just change the two lines I linked above (edited after the fact to add the one in the config file template)? Is that a breaking change? anything to do on the github actions side?

**Comment by beeb** [comment]
I guess the config file in the current state would support both `docs:` and `doc:` since the colon is omitted. Maybe better to keep it like this.

**Comment by orhun** [comment]
> I guess the config file in the current state would support both `docs:` and `doc:` since the colon is omitted. Maybe better to keep it like this.

Yeah, that was the idea. It is probably a breaking change if we change that. I'm not sure but there might be some projects that are still using `git-cliff` with `doc` commits. Thanks for bringing this to our attention though!

**Comment by orhun** [comment]
> But I would change it in `changelog.rs` for sure.

Oh, go ahead!

**Comment by beeb** [comment]
I renamed and edited to be more in line with that I will change in the end.
