### ISSUE TITLE
Re-license under the MIT + Apache 2.0 license

### ISSUE THREAD

**Issue by orhun** [orhun/git-cliff#165]
To all the contributors of `git-cliff`! ⛰

I hope you're doing well. I'm reaching out to discuss a potential change in licensing for the project.

Currently, the project is licensed under [**GPL3**](https://www.gnu.org/licenses/gpl-3.0.en.html), which has certain restrictions on distribution and usage.

I believe that a re-licensing to [**MIT**](https://opensource.org/license/mit/) + [**Apache 2.0**](https://www.apache.org/licenses/LICENSE-2.0) license will provide several benefits to both the project and its users:

- Greater flexibility in terms of usage, distribution, and modification of the codebase.
- Compatibility with a wider range of software licenses, making it easier for other developers to incorporate or build upon the project.
- Reduced legal barriers to adoption by companies and organizations that have policies against using or contributing to GPL3-licensed projects.
- Improved accessibility to potential contributors who may be hesitant to contribute to a project with a more restrictive license.
- The adoption of widely recognized and accepted licenses will provide greater legal certainty and protection to users and contributors alike.

This is also the license of choice for the [Rust project](https://www.rust-lang.org/policies/licenses) itself and you can read more about their reasoning [here](https://github.com/rust-lang/rust/blob/master/COPYRIGHT).

The re-licensing can only be done if _all_ of the below authors consent to re-licensing their work under the terms of the MIT and Apache 2.0 license or if their contributions are _removed_.

The authors of the project have been derived using `git log --all --format='%aN <%aE>' | sort -u`:

```
Aaron Friel <mayreply@aaronfriel.com>
alteregoart <41084168+alteregoart@users.noreply.github.com>
bors[bot] <26634292+bors[bot]@users.noreply.github.com>
Cassandra McCarthy <cassie@7596ff.com>
dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Eliza Weisman <eliza@buoyant.io>
Florian Fromm <flrn.frmm@gmail.com>
Grachev Mikhail <work@mgrachev.com>
Herby Gillot <herby.gillot@gmail.com>
Jan Katins <jasc@gmx.net>
Jeroen Claassens <jeroen.claassens@live.nl>
Kaushal Modi <kaushal.modi@gmail.com>
Kenji Miyake <31987104+kenji-miyake@users.noreply.github.com>
Lygon Bowen-West <l.bowenwest@googlemail.com>
Mack Solomon <macksol@gmail.com>
Marcin Puc <5671049+tranzystorek-io@users.noreply.github.com>
Marco Ieni <11428655+MarcoIeni@users.noreply.github.com>
Matt Foxx <FoxxMD@users.noreply.github.com>
Ömer Faruk Şahin <48451145+ofsahof@users.noreply.github.com>
orhun <orhunparmaksiz@gmail.com>
Orhun Parmaksız <orhunparmaksiz@gmail.com>
Pascal Bach <pascal.bach@nextrem.ch>
pataar <pietering1@gmail.com>
Radu Suciu <radusuciu@gmail.com>
Sayafdine Said <sayafdine.said+github@protonmail.com>
Sebastian Müller <sbmueller@users.noreply.github.com>
Steven L <imgroxx@gmail.com>
Taylan Dogan <git@taylandogan.info>
Tonye Jack <jtonye@ymail.com>
Uy Ha <8091245+uyha@users.noreply.github.com>
```

For convenience, all users with a GitHub account have been added to the below list of checkboxes:

- [x] @orhun
- [x] @MarcoIeni
- [x] @kondanta
- [x] @kenji-miyake
- [x] @bors[bot]
- [x] @tranzystorek-io
- [x] @dependabot[bot]
- [x] @AaronFriel
- [x] @7596ff
- [x] @hawkw
- [x] @FlrnFrmm
- [x] @mgrachev
- [x] @herbygillot
- [x] @jankatins
- [x] @favna
- [x] @kaushalmodi
- [x] <s>@lbowenwest</s> (see #292 & #293)
- [x] @mackness
- [x] @FoxxMD
- [x] @bachp
- [x] @radusuciu
- [x] @musikid
- [x] @sbmueller
- [x] @Groxx
- [x] @jackton1
- [x] @uyha
- [x] @alteregoart
- [x] @pataar
- [x] @ofsahof

The list of contributors is derived using `curl -s https://api.github.com/repos/orhun/git-cliff/contributors | jq -r .[].login | xargs -I {} echo "- [ ] @{}"`

Please leave a comment to this issue stating that you consent to the license change or indicate your objection if you do not agree with the new license terms. For example:

- ✅ I consent to my work on git-cliff to be licensed under the terms of the MIT or Apache 2.0 license. 
- ❌ I object to the proposed license change and do not consent to my work on git-cliff being licensed under either the MIT or Apache 2.0 license.

Thank you for your contributions to the project and your attention to the matter! 🐻

**Comment by pataar** [comment]
✅ I consent to my work on git-cliff to be licensed under the terms of the MIT or Apache 2.0 license.

**Comment by uyha** [comment]
✅ I consent to my work on git-cliff to be licensed under the terms of the MIT or Apache 2.0 license.

**Comment by tranzystorek-io** [comment]
✅ I consent to my work on git-cliff to be licensed under the terms of the MIT or Apache 2.0 license.

**Comment by radusuciu** [comment]
✅ I consent to my work on git-cliff to be licensed under the terms of the MIT or Apache 2.0 license.

**Comment by MarcoIeni** [comment]
✅ I consent to my work on git-cliff to be licensed under the terms of the MIT or Apache 2.0 license.

**Comment by herbygillot** [comment]
✅ I consent to my work on git-cliff to be licensed under the terms of the MIT or Apache 2.0 license.

**Comment by favna** [comment]
✅ I consent to my work on git-cliff to be licensed under the terms of the MIT or Apache 2.0 license.


Sidenote, I didn't even know it was possible to combine 2 licenses like that. TIL.

**Comment by hawkw** [comment]
:white_check_mark: I consent to my work on git-cliff to be licensed under the terms of the MIT or Apache 2.0 license.

**Comment by 7596ff** [comment]
✅ I consent to my work on git-cliff to be licensed under the terms of the MIT or Apache 2.0 license.

**Comment by musikid** [comment]
✅ I consent to my work on git-cliff to be licensed under the terms of the MIT or Apache 2.0 license.

**Comment by FlrnFrmm** [comment]
✅ I consent to my work on git-cliff to be licensed under the terms of the MIT or Apache 2.0 license.

**Comment by AaronFriel** [comment]
✅ I consent to my work on git-cliff to be licensed under the terms of the MIT or Apache 2.0 license.

**Comment by kenji-miyake** [comment]
:white_check_mark: I consent to my work on git-cliff to be licensed under the terms of the MIT or Apache 2.0 license.

**Comment by bachp** [comment]
:white_check_mark: I consent to my work on git-cliff to be licensed under the terms of the MIT or Apache 2.0 license.

**Comment by jankatins** [comment]
✅ I consent to my work on git-cliff to be licensed under the terms of the MIT or Apache 2.0 license.

(I only removed a word from the readme, so I'm irrelevant for this)

**Comment by mgrachev** [comment]
✅ I consent to my work on git-cliff to be licensed under the terms of the MIT or Apache 2.0 license.

**Comment by jackton1** [comment]
✅ I consent to my work on git-cliff to be licensed under the terms of the MIT or Apache 2.0 license.

**Comment by sbmueller** [comment]
✅ I consent to my work on git-cliff to be licensed under the terms of the MIT or Apache 2.0 license.

**Comment by alerque** [comment]
I didn't make the list above, but since I have a PR pending that was submitted under the original licensing I'll pre-empt that being an issue:

:white_check_mark: I consent to my work on git-cliff to be licensed under the terms of the MIT or Apache 2.0 license.

**Comment by kondanta** [comment]
✅ I consent to my work on git-cliff to be licensed under the terms of the MIT or Apache 2.0 license.

**Comment by FoxxMD** [comment]
:white_check_mark: I consent to my work on git-cliff to be licensed under the terms of the MIT or Apache 2.0 license.

**Comment by mackness** [comment]
✅ I consent to my work on git-cliff to be licensed under the terms of the MIT or Apache 2.0 license.

**Comment by ofsahof** [comment]
✅ I consent to my work on git-cliff to be licensed under the terms of the MIT or Apache 2.0 license.

**Comment by PSeitz** [comment]
I consent to my work on git-cliff to be licensed under the terms of the MIT or Apache 2.0 license.

**Comment by tvcsantos** [comment]
✅ I consent to my work on git-cliff to be licensed under the terms of the MIT or Apache 2.0 license.

**Comment by alexfertel** [comment]
✅ I consent to my work on git-cliff to be licensed under the terms of the MIT or Apache 2.0 license.

**Comment by orhun** [comment]
I couldn't reach out to @lbowenwest so his GPL contributions are removed in #292 and we rewrote the same functionality in #293

**Comment by joshka** [comment]
I consent to the 2 PRs that revert the leftover GPL code in #292 and then update the clap version in #293 to be relicensed under the MIT and/or Apache 2 license.
