### ISSUE TITLE
Can't install v0.4.0 from cargo

### ISSUE THREAD

**Issue by TommasoAmici** [orhun/git-cliff#19]
**Describe the bug**
I can't get cargo to update git-cliff to v0.4.0 (I'm on v0.3.0). I tried to uninstall and install again, but it fetches v0.3.0

**To Reproduce**
1. Install v0.3.0
2. Attempt to upgrade to v0.4.0
3. See error

or

1. Uninstall v0.3.0
2. Attempt to install v0.4.0
3. See error

**Expected behavior**
I expect to be able to update or install the new version

**Screenshots/Logs**
error: could not find `git-cliff` in registry `crates-io` with version `=0.4.0`

![image](https://user-images.githubusercontent.com/424525/135766860-8aff3135-5ac9-44aa-973d-9ec39cddb311.png)

![image](https://user-images.githubusercontent.com/424525/135766872-a5d9a0aa-2572-49ce-a773-21f1c085322c.png)

**System (please complete the following information):**
 - OS Information: macOS 11.6
 - Project Version: 0.3.0

**Comment by orhun** [comment]
I cannot reproduce this. I tried the following:

```sh
cargo install git-cliff --version 0.3.0
cargo install git-cliff --version 0.4.0
```

Can you try again? This might be a one-time issue about `crates.io` or local cache.

**Comment by TommasoAmici** [comment]
I cleared my `~/.cargo` directory and then it worked, weird. I'll close the issue
