### ISSUE TITLE
Unable to use the author name inside the the commit_parsers

### ISSUE THREAD

**Issue by nachtien** [orhun/git-cliff#194]
**Describe the bug**

I am trying to put commits that come from Renovate bot in their own group. I was trying to accomplish this via the author.name or author.email but neither seemed to work.

**To reproduce**
```toml
commit_parsers = [
    { author.name = "Renovate Bot", group = "Dependency Updates"},
    { message = ".*", group = "Uncategorized"},
]
```

outputted context with Renovate:

```json
{
  "id": "768e5913a9d519b58d16a90714c92b19f8971c",
  "message": "Update dependency androidx.arch.core:core-testing from v2.1.0 to v2.2.0\n",
  "group": null,
  "scope": null,
  "links": [],
  "author": {
    "name": "Renovate Bot",
    "email": "group1162_bot@noreply.gitemail",
    "timestamp": 1677115782
  },
  "committer": {
    "name": "Nick",
    "email": "nachtien@myemail.com",
    "timestamp": 1677190457
  },
  "conventional": false
},
```

**Expected behavior**

I expect to be able to access the author name/email in the commit_parsers

**Software information**

- Operating system: Mac m1
- Rust version: not installed
- Project version: 1.2.0

**Comment by orhun** [comment]
Implemented in #312
