### ISSUE TITLE
Some commits are being read in with a trailing new line at the end of the message

### ISSUE THREAD

**Issue by nachtien** [orhun/git-cliff#195]
**Describe the bug**

The outputted context of the commit:
```json
{
  "id": "339e3e129e043a197c3bc7379e12d95b94145",
  "message": "my commit message\n",
  "group": null,
  "scope": null,
  "links": [],
  "author": {
    "name": "Nick Achtien",
    "email": "nachtien@myeamil.com",
    "timestamp": 1682610606
  },
  "committer": {
    "name": "Nick Achtien",
    "email": "nachtien@myeamil.com",
    "timestamp": 1682610606
  },
  "conventional": false
}
```

**To reproduce**
This happens with every cliff.toml example in this the git-cliff examples folder. 
We are using Gitlab.
Besides some of our own commits, this is happening with every commit that Renovate makes.
-->

Adding trim_end in the template fixes this issue.

**Expected behavior**

There shouldn't be any trailing lines

**Screenshots / Logs**

**Software information**

- Operating system: Mac M1
- Project version: 1.2.0

**Comment by orhun** [comment]
Hey, thanks for reporting!

This is now fixed in #403
