### ISSUE TITLE
Global configuration file and builtin configuration

### ISSUE THREAD

**Issue by toyboot4e** [orhun/git-cliff#2]
Hi, `git-cliff` is cool stuff!

**1. Is your feature request related to a problem? Please describe.**
I'd like to not put `cliff.toml` in my repository when I use `git-cliff` just as an alternative to `git log`.

**2. Describe the solution you'd like**
`git-cliff` locates `cliff.toml` in `~/.config/git-cliff/cliff.toml`. If no configuraiton file is found, `git-cliff` uses default (builtin) configuration.

**3. Describe alternatives you've considered**
`git-cliff` looks into `GIT_CLIF_CONFIG` environment variable.

**4. Additional context**
Default configuration removes the need of copying `cliff.toml`, so it would help first-time users.

**Comment by orhun** [comment]
With the `v0.2.*` release:
- default configuration file is embedded into the binary and it is used if no configuration file is specified
- this embedded configuration file can be saved to `cliff.toml` via `git cliff --init`
- configuration file is read from `$HOME/.config/git-cliff/cliff.toml` if the path exists

Closing, thank you for submitting this issue!
