### ISSUE TITLE
Running git cliff in the Gitlab CI results in an 'IO error'

### ISSUE THREAD

**Issue by pataar** [orhun/git-cliff#20]
// offtopic: git-cliff is my favourite changelog generation tool after trying a lot of them. So thanks for that!

**Describe the bug**
When running git-cliff in the Gitlab CI. The tool results an IO error. Not sure where to go from here. Executing `pwd` gives the correct path, that includes a `.git` directory.

**Expected behavior**
It would run in the same way as it does locally.

**Screenshots/Logs**
![image](https://user-images.githubusercontent.com/3403851/137306706-544daeb6-6155-48a0-9ab2-b4df90b206ff.png)

**System (please complete the following information):**
 - OS Information: CI image is an alpine based image
 - Project Version: 0.4.0 musl

**Comment by pataar** [comment]
> In your case, maybe `git-cliff` cannot access the current directory due to insufficient permissions. Can you check this with another command?
> 
> >

The permissions are correct. So it must be something else. It's running in an alpine container.

**Comment by orhun** [comment]
Any updates on this?

**Comment by DeveloperC286** [comment]
Just read the generated description into a variable like I am doing on GitLab.

```
RELEASE_DESCRIPTION=$(./git-cliff ${LATEST_TAG}.. --tag "${NEW_TAG}")
```

**Comment by EvanCarroll** [comment]
I am also getting this error.

**Comment by orhun** [comment]
Do you mind creating a new issue with relevant data? @EvanCarroll

**Comment by EvanCarroll** [comment]
@orhun  I can't confirm it. I've since lost my job. I believe the problem occurs when you use `--prepend` and the config file does not exist. I believe that's how I got it anyway.
