### ISSUE TITLE
Add GitLab CI usage example to README.md

### ISSUE THREAD

**Issue by orhun** [orhun/git-cliff#21]
**Is your feature request related to a problem? Please describe.**
It would be nice to see an example in the documentation for the usage of `git-cliff` with GitLab CI.

**Describe the solution you'd like**
Add an example `.gitlab-ci.yml` to [README.md](https://github.com/orhun/git-cliff/blob/main/README.md), preferably after the [github-action](https://github.com/orhun/git-cliff#github-action) section.

**Describe alternatives you've considered**
None

**Additional context**
#20

**Comment by alteregoart** [comment]
and this solution work fine on this repo https://gitlab.com/alteregoart/git-cliff-test (on the docs.gitlab-ci.yml)

**Comment by orhun** [comment]
> and this solution work fine on this repo [gitlab.com/alteregoart/git-cliff-test](https://gitlab.com/alteregoart/git-cliff-test) (on the docs.gitlab-ci.yml)

Awesome! Do you mind submitting a PR to add this example to README.md?
