### ISSUE TITLE
Use regex for `tag_pattern`

### ISSUE THREAD

**Issue by PoisonPhang** [orhun/git-cliff#289]
**Is your feature request related to a problem? Please describe.**

I find myself struggling to define a sem-version filter using basic glob filtering that is used when parsing `tag_pattern`. This is especially annoying when all other tag filtering fields (`skip_tags` and `ignore_tags`) use regex.

**Describe the solution you'd like**

It would be great if we could use regex (or even extglob) to define `tag_pattern`.

**Comment by woshilapin** [comment]
I'll take a stab at this one.
