### ISSUE TITLE
Fix typos in the changelog

### ISSUE THREAD

**Issue by orhun** [orhun/git-cliff#310]
**Is your feature request related to a problem? Please describe.**

There are some typos in the changelog and it would be nice to fix them.

Unfortunately we can't just push a commit to fix them since the changelog is re-generated with each release.

**Describe the solution you'd like**

1. Spot the typo commits with `typos` or `codespell`.
2. Update the default changelog configuration for pre-processing the commit messages.

**Describe alternatives you've considered**

Or use post-processors to update the final changelog.

**Additional context**

There is already a PR for this at #304 but seems inactive.

**Comment by woshilapin** [comment]
Hey there, I'd like to work on that one (and #311 at the same time).
