### ISSUE TITLE
record additional information in `Commit`: `is_merge_commit` and `is_merged`

### ISSUE THREAD

**Issue by jan-ferdinand** [orhun/git-cliff#321]
My current git workflow is to develop a feature on its branch, then merge that branch and describe the corresponding changes in the merge commit. The development phase of the feature is unimportant for my changelog: only the final merge commit matters. The behavior of git-cliff I currently observe is that all commits are considered, even if they live on a now-merged feature branch.[^1]

[^1]: Interestingly, #85 seems to describe the behavior I'd like to achieve, but they would like to have the behavior I am currently observing.

I'd love to be able to filter for
- merge commits, and
- commits living on some branch that has been merged.

Following [this suggestion](https://github.com/orhun/git-cliff/issues/85#issuecomment-1511998434) made in #85, the `Commit` struct could record the information necessary using the two additional fields `is_merge_commit` and `is_merged`.

I am by no means a git expert, but if I understand the git book correctly, this should be feasible from a technical standpoint. This belief is largely based on [chapter 10.3 “Git Internals”](https://git-scm.com/book/en/v2/Git-Tools-Revision-Selection), paragraph “Ancestry References”:
> the first parent of a merge commit is from the branch you were on when you merged (frequently `master`), while the second parent of a merge commit is from the branch that was merged (say, `topic`)

This suggests to me that no heuristics are necessary to gather the necessary information.

As a fallback, I was looking for (but could not find) a way to specify a list of commits[^range] that are to be ignored. This would allow me to manually list the commits I consider too “noisy”. Even though that is laborious, at least it's persisted.

[^range]: or better yet, a range of commits

If I understand matters correctly, the feature request made here is a superset of the behavior desired in #143.

**Comment by orhun** [comment]
Hello! Thanks for creating this and sorry for the late reply.

- `is_merge_commit`: I implemented that in #389 
- `is_merged`: I didn't quite get how to set that value. I looked into [`git2`](https://docs.rs/git2/latest/git2/) API but still not sure how to set it.

**Comment by jan-ferdinand** [comment]
> sorry for the late reply

No worries. :blush:

> * `is_merge_commit`: I implemented that in [feat(commit): add merge_commit flag to the context #389](https://github.com/orhun/git-cliff/pull/389)

Nice! :tada:

> * `is_merged`: I didn't quite get how to set that value.

I think it might possible with [`git merge-base`](https://stackoverflow.com/a/13526591) and potentially some additional pre-∧/∨post-processing. I'm not sure how that translates to `git2`. In any case, I'm not convinced this is even a desirable feature – even though I'm the one who requested it in the first place. :upside_down_face:

Closing for now. Thanks for looking into it! :relieved:
