### ISSUE TITLE
Add a CLI flag for disabling the command execution

### ISSUE THREAD

**Issue by orhun** [orhun/git-cliff#333]
**Is your feature request related to a problem? Please describe.**

The default config of `git-cliff` now runs [`typos`](https://github.com/crate-ci/typos/) to fix the typos in the commits:

https://github.com/orhun/git-cliff/blob/3c2fb6072612a38ab7c6ea41e7c2ae34435fde99/cliff.toml#L66-L71

Thus generating a changelog for the whole git history takes some time. 

**Describe the solution you'd like**

We should add a command-line flag for disabling command execution in the cases where the user wants to generate a changelog without running external commands.

For example, `git-cliff --no-exec` will skip executing the commands defined in `replace_command`.

**Describe alternatives you've considered**

None.

**Additional context**

See #316 for additional discussion about `typos` implementation.

**Comment by orhun** [comment]
Hello @mamaicode 👋🏼 

Yup, are you interested in making a PR? 🐻

**Comment by mamaicode** [comment]
Yep! Will look into this

**Comment by orhun** [comment]
Kindly ping 🐻 do you need any guidance on this?
