### ISSUE TITLE
Firefox / Noto Sans / GitHub horribly screws with this project

### ISSUE THREAD

**Issue by alerque** [orhun/git-cliff#340]
Somewhere along the line a recent FireFox build / Noto Sans font update / GitHub style update broke the `ff` ligature and started rendering it as `fi` — to disastrous effect for this project.

Not that this project is to blame or can fix it, but for posterity:

![20231106_12h12m06s_grim](https://github.com/orhun/git-cliff/assets/173595/cea39884-77b9-4adc-8ed6-be8e4a9dcea2)

I'll link upstream bugs if I figure out where the actual blame lies.

**Comment by orhun** [comment]
lmao
