### ISSUE TITLE
Bump does not work properly

### ISSUE THREAD

**Issue by o4rz3l** [orhun/git-cliff#343]
**Describe the bug**

Bump does not reliably bump the version e.g. for a minor change ( feat: ) .In addition sometimes it produces "null" as next version (but i have not found a way to reproduce it).

BTW Just an idea: git cliff --bump --unreleased should offer to create the tag "v0.0.1" if no tag is set before.
**To reproduce**

**Expected behavior**

It should be bumped to 0.1.0.

**Screenshots / Logs**

![image](https://github.com/orhun/git-cliff/assets/98393628/57272339-58e6-4c6e-b195-d27a3aeb30be)

**Software information**

- Operating system: Win10 as well as WSL2 
- Project version: git-cliff 1.4.0

**Comment by orhun** [comment]
Hello, thanks for reporting this!

> git cliff --bump --unreleased should offer to create the tag "v0.0.1" if no tag is set before.

Created #344

> It should be bumped to 0.1.0.

Not sure what happened there, maybe ping @marcoIeni who is the author of [next_version](https://crates.io/crates/next_version).

**Comment by MarcoIeni** [comment]
> It should be bumped to 0.1.0.

This is not how the `next_version` library works. I clarified it in https://github.com/MarcoIeni/release-plz/issues/1064

**Comment by orhun** [comment]
I think this behavior is fine as long as it is documented in `git-cliff` as well, does anyone volunteer to add that?

**Comment by orhun** [comment]
The behavior has changed to support this use case in 4eef684c568ad16357e5d256180a51b1a46dd0cb
