### ISSUE TITLE
Set tag to `v0.0.1` via `--bump` if no tags exist

### ISSUE THREAD

**Issue by orhun** [orhun/git-cliff#344]
**Is your feature request related to a problem? Please describe.**

> git cliff --bump --unreleased should offer to create the tag "v0.0.1" if no tag is set before.

**Describe the solution you'd like**

Self-explanatory.

**Describe alternatives you've considered**

None.

**Additional context**

See #343

**Comment by liuyinz** [comment]
@orhun Many projects start from v0.1.0 with the major.minor.patch style, right?  I guess v0.0.1 would be annoying...

**Comment by orhun** [comment]
@liuyinz fair point! I updated it to use `0.1.0` in 3123fd2eac0da0e800923d8b9f3c86bc6814edd4
