### ISSUE TITLE
Bump does not work with tag prefixes

### ISSUE THREAD

**Issue by jsurkont** [orhun/git-cliff#347]
**Describe the bug**

Running `--bump` with tags contain a prefix fails. This issue is especially relevant for monorepos, where, _I think_, a common pattern is to use `package/` as a tag prefix, e.g., `foo/0.2.1`, `bar/0.4.2`.

**To reproduce**

```bash
$ cat cliff.toml -p
[git]
tag_pattern = "foo/[0-9].*"
$ git commit --allow-empty -m "feat: initial commit"
$ git tag foo/0.1.0
$ git commit --allow-empty -m "fix: fix some bugs"
$ git log --oneline
42eb0ec (HEAD -> main) fix: fix some bugs
dff35ef (tag: foo/0.1.0) feat: initial commit
$ git cliff --unreleased  # it works as expected, only commits since the last tag are included
 WARN  git_cliff > Changelog body is not specified, using the default template.
## [unreleased]

### Fix

- Fix some bugs
$ git cliff --unreleased --bump
 WARN  git_cliff > Changelog body is not specified, using the default template.
 ERROR git_cliff > Semver error: `unexpected character 'f' while parsing major version number`
```
**Expected behavior**

The command should _not_ fail.

**Software information**

- Project version: git-cliff 1.4.0
- Operating system: macOS 13.6.1
- Rust version: 1.72.1

**Comment by orhun** [comment]
Hello! 🐻
Thanks for creating the issue. This feature is now implemented in 2399e57fd3b715875d5dc3897fad85a70cc199eb
I added a bunch of unit tests so it should be fine. Feel free to [build from source](https://git-cliff.org/docs/installation/build-from-source) and test it out!
