### ISSUE TITLE
Set default output as `CHANGELOG.md`

### ISSUE THREAD

**Issue by sh-cho** [orhun/git-cliff#352]
`-o, --output <PATH> ... [default: CHANGELOG.md]`

I think `CHANGELOG.md` is good to be default. How do you think?

**Comment by orhun** [comment]
In that case the behavior should be:

```sh
$ git cliff # outputs to stdout

$ git cliff -o # outputs to CHANGELOG.md

$ git cliff -o OTHER_FILE.md # outputs to another file
```

If achieving this is possible via `clap` then I think it would be great to have this!

Are you interested in investigating this/potentially making a PR?

**Comment by sh-cho** [comment]
Yep :)
I will make a patch in my free time

**Comment by orhun** [comment]
Great, thanks!
