### ISSUE TITLE
Allow returning bumped version without entire changelog

### ISSUE THREAD

**Issue by nappa85** [orhun/git-cliff#361]
In my understanding, main usage implies passing a tag version from outside, like in https://github.com/orhun/git-cliff/blob/main/release.sh

Then, I can't understand how to use the `--bump` option, since it prints the entire changelog, therefore, if I don't want to use other tools, I'm forced to grep out new version from the produced changelog to be able to create the tag.

It would be nice to have a subcommand to only have the tag name

**Comment by orhun** [comment]
Hello!

> Then, I can't understand how to use the --bump option, since it prints the entire changelog, therefore, if I don't want to use other tools, I'm forced to grep out new version from the produced changelog to be able to create the tag.

You can simply do:

```sh
git cliff --unreleased --bump --context | jq -r .[0].version
```

This is also what we use for `git-cliff-action`: https://github.com/orhun/git-cliff-action/blob/b7913b664658dd091d9971658cb02a19047baa79/entrypoint.sh#L41

Only downside is you need to have `jq` installed to parse JSON.

**Comment by orhun** [comment]
Now possible with `--bumped-version`.
