### ISSUE TITLE
`sort_commits` doesn't work but `--sort` does

### ISSUE THREAD

**Issue by azzamsa** [orhun/git-cliff#39]
**Describe the bug**
I want my commits to be sorted by the newest time. However, it does not work using `sort_commits = "newest"` but it works using `--sort newest`

**To Reproduce**
1. `git clone https://github.com/orhun/git-cliff`
2. `cd git-cliff`
3. `git-cliff --config config/cliff.toml --tag 0.1.0-beta.3`

![image](https://user-images.githubusercontent.com/17734314/144531887-7f11dedf-2ca0-4268-9ac8-1456c1b4ad1c.png)

4. change `sort_commits = "oldest"` to `sort_commits = "newest"` in `/git-cliff/config/cliff.toml`
the run the same command `git-cliff --config config/cliff.toml --tag 0.1.0-beta.3`

![image](https://user-images.githubusercontent.com/17734314/144532070-b1df0f3c-c3c1-449f-9258-1d4d6615f36b.png)

**The order is same. no chages**

---

5. Now, remove the `sort_commits = "newest"` line the config.
6. run ` git-cliff --config config/cliff.toml --tag 0.1.0-beta.3 --sort newest` and ` git-cliff --config config/cliff.toml --tag 0.1.0-beta.3 --sort oldest`. **Now it works**.
7. Got the error?

**Expected behavior**
`sort_commits = "newest"` should output the same exact thing as `--sort newest`

**Screenshots/Logs**
Attached.

**System (please complete the following information):**
```
❯ git-cliff --version
git-cliff 0.4.2, version: https://github.com/orhun/git-cliff/commit/02a6187a58583f27e4604d7ea518b52b4bc7a833

OS: Debian GNU/Linux 11 (bullseye)
Kernel: Linux 5.10.0-9-amd64 x86_64
```

**Additional context**
Thanks for git-cliff.

**Comment by azzamsa** [comment]
I did `cargo install git-ciff -f`, but the issue still there. 

I cant make sure since we don't have a git hash in our `--version`

**Comment by orhun** [comment]
> I did `cargo install git-ciff -f`, but the issue still there.

`cargo install` does not pull the latest revision from git. You can [build from source](https://github.com/orhun/git-cliff#build-from-source) or use [docker images](https://hub.docker.com/r/orhunp/git-cliff) to try it out until a new version is published.

**Comment by azzamsa** [comment]
Oh, OK.

Now runni `./target/release/git-cliff  --config config/cliff.toml --tag 0.1.0-beta.3` solves the issue.

Thanks a lot for git-cilff, Orhun.
