### ISSUE TITLE
Add breaking_description

### ISSUE THREAD

**Issue by rockandska** [orhun/git-cliff#4]
**Is your feature request related to a problem? Please describe.**
A new release of git_conventionnal was just published who add [breaking_description](https://docs.rs/git-conventional/0.10.0/git_conventional/struct.Commit.html#method.breaking_description)

**Describe the solution you'd like**
Add breaking_description to the available meta

**Additional context**
Could be used to generate `Breaking Changes` section in template easily.

**Comment by orhun** [comment]
It will be available starting from the next release. (`0.2.5+`) Thank you!
