### ISSUE TITLE
Errors out with `ERROR git_cliff > IO error: Broken pipe (os error 32)` when piping

### ISSUE THREAD

**Issue by hauleth** [orhun/git-cliff#407]
**Describe the bug**

Various CLI utilities can force closing previous program in pipeline by closing pipe when they are done. Example of such too is `head` which will exit (and close pipe) when it reaches requested number of lines. However this causes `git-cliff` to close abnormally because of the write error.

**To reproduce**

Run:

```
$ git cliff | head -n1
# Changelog
 ERROR git_cliff > IO error: `Broken pipe (os error 32)`
```

**Expected behavior**

```
$ git cliff | head -n1
# Changelog
```

**Software information**

- Operating system: `Darwin 23.2.0 arm64`
- Rust version: Installed via Nixpkgs, so no idea
- Project version: `1.4.0`

**Comment by orhun** [comment]
Hello, thanks for reporting this! 🐻 

It is now fixed in bdce4b504e0b1984283ad056931fc4fe7b893dc3

See https://github.com/Misterio77/flavours/issues/16 and https://github.com/rust-lang/rust/issues/46016 for more context.
