### ISSUE TITLE
scopes `(*)` are skipped

### ISSUE THREAD

**Issue by tami5** [orhun/git-cliff#43]
**Describe the bug**

When commit scope is `(*)` or `*` it isn't generated

**To Reproduce**
1. commit with something like `feat(*): user authentication`
2. generate
3. missing

**Expected behavior**
the item get added with default_scope and to be treated as if it's `feat: user authentication`

**System (please complete the following information):**
 - OS Information: MacOS
 - Project Version: [0.4.0]

**Additional context**

cliff configuration: https://gist.github.com/tami5/1044c256a173c622847114cc3bcd0ffd

**Comment by orhun** [comment]
Hello! I can't reproduce this.

When I have `feat(*): user authentication` in my commit history, I can generate the following changelog with the config you provided:


```
# Changelog

# [unreleased](https://github.com/orhun/git-cliff)

## <!-- 0 -->✨ Features

##### (*)

- <a href="https://github.com/orhun/git-cliff/commit/411a6f76c0ddb690a213b2a9d12a3a9481540104"><tt>411a6f7</tt></a> User authentication
```

Or did you mean something else while saying "it isn't generated"? Do you want to assume that these type of commits have a general scope (and is that the reason why you used `*`?) Can you please elaborate your use-case?

**Comment by tami5** [comment]
> Hello! I can't reproduce this.
> 
> 
> 
> When I have `feat(*): user authentication` in my commit history, I can generate the following changelog with the config you provided:
> 
> 
> 
> 
> 
> ```
> 
> # Changelog
> 
> 
> 
> # [unreleased](https://github.com/orhun/git-cliff)
> 
> 
> 
> ## ✨ Features
> 
> 
> 
> ##### (*)
> 
> 
> 
> - <a href="https://github.com/orhun/git-cliff/commit/411a6f76c0ddb690a213b2a9d12a3a9481540104"><tt>411a6f7</tt></a> User authentication
> 
> ```
> 
> 
> 
> Or did you mean something else while saying "it isn't generated"? Do you want to assume that these type of commits have a general scope (and is that the reason why you used `*`?) Can you please elaborate your use-case?
> 
> 

Oh that's odd, It didn't generate in my case at all, can I invite you to the repo? I'd make it public but isn't ready yet.

Yes, in my use case and for consistency reasons I donate the general scope with `(*)`, instead of the total omission the parentheses. I think this common enough to treat it as if it's written like `feat: user authentication`

**Comment by orhun** [comment]
> Oh that's odd, It didn't generate in my case at all, can I invite you to the repo? I'd make it public but isn't ready yet.

Sure, or you can share a snippet from the commit history if that's alright. It depends on how you want me to test this.

> Yes, in my use case and for consistency reasons I donate the general scope with `(*)`, instead of the total omission the parentheses. I think this common enough to treat it as if it's written like `feat: user authentication`

I see. Well, in this case, having `(*)` in the changelog is not really what you want then. It should be somehow overrode to remove/replace the scope. However, this is not currently possible because there isn't a commit pre-processing mechanism implemented in `git-cliff` yet.

**Comment by orhun** [comment]
[Commit preprocessors](https://github.com/orhun/git-cliff#commit_preprocessors) feature has been implemented.
