### ISSUE TITLE
Make the bump version rules configurable

### ISSUE THREAD

**Issue by jsurkont** [orhun/git-cliff#447]
**Is your feature request related to a problem? Please describe.**

The new `bump` flag is great! However, since 4eef684c568ad16357e5d256180a51b1a46dd0cb the default behavior for zero-based releases is problematic, i.e. features always bump the minor version, while breaking changes bump the major version, including from 0 to 1. I think this is an undesired behavior for projects following the bump rules described in [next_version](https://docs.rs/next_version/latest/next_version/).

**Describe the solution you'd like**

I think it should be possible to opt out from the default behavior. That is, the hardcoded values in

https://github.com/orhun/git-cliff/blob/4eef684c568ad16357e5d256180a51b1a46dd0cb/git-cliff-core/src/release.rs#L117-L118

should take values form the configuration instead.

**Describe alternatives you've considered**

I couldn't think of any alternative (other than forking the project).

**Additional context**

If you would be interested, I could write a PR for it.

**Comment by ribeaud** [comment]
Any news or opinion on that one? We would be interested as well...

**Comment by orhun** [comment]
Hello! I think it would be nice to have this, @jsurkont are you still interested in creating a PR?

**Comment by jsurkont** [comment]
Hello @orhun! Yes, I still am. I'll create a PR soon.
