### ISSUE TITLE
Configure from section in Cargo.toml

### ISSUE THREAD

**Issue by alerque** [orhun/git-cliff#46]
Having a separate config file just for a few values (hint hint #45) seems like overkill.

It seems like it would be pretty easy to check for a custom section in Cargo.toml for Rust projects. As a bonus with some json maybe also look at package.json, pyproject.toml, etc. Most of these formats allow project meta data in custom keys.

**Comment by orhun** [comment]
Hey, although I'm a proponent of not adding language-specific features to `git-cliff`, it makes sense to drop the need for a config file altogether and place the configuration inside an already existing manifest per se.

On that note, can you share examples to demonstrate how it might look like for the formats you mentioned? I think the first place to start implementing this is obviously `Cargo.toml` so it would be nice to get an idea.

**Comment by alerque** [comment]
Here is an example of a similar use case, specifically using `standard-version` tooling on a JS project. The conventional commit settings such as allowed types just gets added to the existing package.json file:

https://github.com/sile-typesetter/sile/blob/master/package.json#L36-L85

I'll try to come up with an example for a similar situation using Cargo.toml and adapt it far what it would look like with `git-cliff` settings.

**Comment by orhun** [comment]
> Here is an example of a similar use case, specifically using `standard-version` tooling on a JS project. The conventional commit settings such as allowed types just gets added to the existing package.json file:
> 
> [sile-typesetter/sile@`master`/package.json#L36-L85](https://github.com/sile-typesetter/sile/blob/master/package.json?rgh-link-date=2022-01-24T07%3A48%3A24Z#L36-L85)

It could be useful in the future. I'd like to focus on `Cargo.toml` first though.

So I think custom metadata can be placed in `Cargo.toml`. One example from `cargo-release`: 

https://github.com/crate-ci/cargo-release/blob/8908982c5b86ebc394047ca288c7a2a0abfe25d6/Cargo.toml#L20

> I'll try to come up with an example for a similar situation using Cargo.toml and adapt it far what it would look like with `git-cliff` settings.

Do you have any updates on this?

**Comment by alerque** [comment]
> Do you have any updates on this?

Nope, I've been distracted down other rabbit holes.

But yes that example from `cargo-release` is similar to what I remember seeing.

**Comment by orhun** [comment]
I pushed [f48d207](https://github.com/orhun/git-cliff/commit/f48d2077c33b878337edc2e5fe8a97be990b4773) which means **git-cliff** can be configured inside `Cargo.toml` now! 🥳

For more information, see [README.md](https://github.com/orhun/git-cliff#project-integration).
