### ISSUE TITLE
Allow parsing merge commits by PR label

### ISSUE THREAD

**Issue by sambolias** [orhun/git-cliff#461]
**Is your feature request related to a problem? Please describe.**

I have been mapping merge commits by specific PR (issue) labels to changelog sections using a different tool which is no longer working, and want to migrate my setup to git cliff. There is no way to do that currently with git cliff. 

**Describe the solution you'd like**

It looks like the functionality to select only merge commits into a branch exists. The commit parser should be able to map/group commit messages to specific sections already. So I believe if that parser also supported matching github issue labels attached those commits I should be able to replicate my old setup. 

**Describe alternatives you've considered**

The github release feature allows some customization, which would support mapping issue labels to sections, and excluding commits with specific labels. But it doesn't allow for multiple projects in a repo, so it wouldn't work with my current setup. 

auto-changelog might do part of what I need. or just manual changelogs. haven't been able to find the perfect tool yet, and doesn't seem reasonable to backfix my git history to put labels in commit messages or anything like that.

**Comment by orhun** [comment]
I implemented this in #467 so the GitHub metadata now contains the PR label information as well.

For example, you can do the following if you want to group the commits by their label:

```jinja2
{% for _groups, commits in commits | group_by(attribute="github.pr_labels") %}

  {%- set groups = _groups | trim_start_matches(pat="[") | trim_end_matches(pat="]") | trim | split(pat=",") -%}
  {%- set_global labels = [] -%}
  {%- for group in groups -%}
    {% set_global label = group | trim_start_matches(pat='"') | trim_end_matches(pat='"') %}
    {% set_global labels = labels | concat(with=label) %}
  {%- endfor -%}

  {%- if labels | length > 1 %}
    ### {{ labels | join(sep=" & ") }}
      {% for commit in commits %}
       
       // list commits       

    {%- endfor -%}
  {%- endif -%}
{%- endfor -%}

``` 

It is messy because Tera's `group_by` filter stringifies the key which means labels are converted to `["test1", "test2"]` - I process this string to form an array again in the example above.
