### ISSUE TITLE
Using git cliff --bump produces "Previous version is not found for calculating the next release." error

### ISSUE THREAD

**Issue by tachojelev** [orhun/git-cliff#473]
**Describe the bug**

I have an existing CHANGELOG with entry for a single release (1.0.0)
There is only one new commit after that release. After I execute `git cliff --bump`, I get `ERROR git_cliff > Previous version is not found for calculating the next release.`.

**To reproduce**

1. Use the following CHANGELOG:

# Changelog

All notable changes to this project will be documented in this file.

### Bug Fixes

- [SCARA-10354] add fix 1
- [SCARA-10354] Add fix 2
- [SCARA-10354] Add fix 3
- [SCARA-10354] Add fix 4

### Features

- [SCARA-10354] Add feature 3

3. Execute `git cliff --bump`
4. Error is returned: `ERROR git_cliff > Previous version is not found for calculating the next release.`

**Expected behavior**

The CHANGELOG should be updated with the new version.

# Changelog

All notable changes to this project will be documented in this file.

### Features
...

### Bug Fixes

- [SCARA-10354] add fix 1
- [SCARA-10354] Add fix 2
- [SCARA-10354] Add fix 3
- [SCARA-10354] Add fix 4

### Features

- [SCARA-10354] Add feature 3

**Screenshots / Logs**

**Software information**

- Operating system: 
- Rust version: 
- Project version: **1.4.0**

**Additional context**

**Comment by orhun** [comment]
This issue will be fixed in the new version. You can try [building from source](https://git-cliff.org/docs/installation/build-from-source) or wait for it 🐻
