### ISSUE TITLE
Using `git cliff --init github` generates an entire changelog, rather than grouping by tags / releases.

### ISSUE THREAD

**Issue by dessalines** [orhun/git-cliff#485]
**Describe the bug**

Running `git cliff --init github` then *any* command, outputs the entire git changelog.

The only way I've found around this, is to do `git cliff MY_LAST_TAG..HEAD --tag MY_NEXT_TAG`

**To reproduce**

Testing on my own repo:

```sh
cargo install --git https://github.com/orhun/git-cliff
git clone https://github.com/dessalines/thumb-key
cd thumb-key
git cliff --init github
git cliff
```

**Expected behavior**

It should be grouped by tag, or limited by unreleased.

**Software information**

`main` branch

- Operating system: Arch linux
- Rust version: Rust 1.75.0
- Project version: main

**Comment by orhun** [comment]
Hey, it looks like your tags does not start with `v` which causes `git-cliff` to skip them. I upstreamed a patch here: https://github.com/dessalines/thumb-key/pull/781
