### ISSUE TITLE
Github enterprise support

### ISSUE THREAD

**Issue by Finkregh** [orhun/git-cliff#508]
Thanks for this project!

**Is your feature request related to a problem? Please describe.**

I'd like to use the github-api related features (e.g. note about first contributions) with github enterprise.

**Describe the solution you'd like**

All github related variables should not be hardcoded like https://github.com/orhun/git-cliff/blob/main/git-cliff-core/src/github.rs#L37 but overwritable via environment variables or config.

**Describe alternatives you've considered**

- Not using github-related features for now.
- changing the variable and compiling locally

**Additional context**

Version: `git-cliff 2.0.2`

Neither running it with `GITHUB_API_URL=https://costomdomain.tld/api/v3/`, nor changing the domain in the macro https://github.com/orhun/git-cliff/blob/main/examples/github-keepachangelog.toml#L17 does help.

```text
 DEBUG git_cliff_core::github    > Sending request to: https://api.github.com/repos/org/testrepo/pulls?per_page=100&page=5&state=closed
 DEBUG reqwest::connect          > starting new connection: https://api.github.com/
```

Compiling with changed API_URL does work.

**Comment by orhun** [comment]
Hey, thanks for reporting! This is now implemented in #512
