### ISSUE TITLE
Broken commit links in Release changelog

### ISSUE THREAD

**Issue by welpo** [orhun/git-cliff#513]
In [Release v2.0.4](https://github.com/orhun/git-cliff/releases/tag/v2.0.4), commit links in the release description are broken. More specifically, they are missing the owner/repo info.

The first link is:

```
https://github.com///commit/819969924bbad25484971c84a4c8d02ae48f1db9
```

When it should be 

```
https://github.com/orhun/git-cliff/commit/819969924bbad25484971c84a4c8d02ae48f1db9
```

Perhaps related to https://github.com/orhun/git-cliff/commit/1aaa9b2150f539116007afc199f57a61bbe4ee20?

Links in the full `CHANGELOG.md` file are fine.

**Comment by orhun** [comment]
Good catch sir! I just fixed them manually.

It is probably due to some git shenanigans - not being able to get the remote automatically. So I pushed 0e46500199f9b7cc7c83a51499f6e90a2adf5888 to fix it.

**Comment by welpo** [comment]
I'm curious: why not set it in `cliff.toml`?

**Comment by orhun** [comment]
That also works. I guess I just went with updating `cd.yml` this time 😄
