### ISSUE TITLE
Add empty releases with configurable placeholder text.

### ISSUE THREAD

**Issue by akarmes** [orhun/git-cliff#518]
**Is your feature request related to a problem? Please describe.**

I'd like a have a possibility to generate an empty changelog entry with a placeholder text like "This release does not include any relevant changes", when parser don't include any commits (omits non relevant once).

**Additional context**

I'm working on a codebase with several changelogs (public and internal) and parsers are configured to exclude some commit types for public changelog. With current behaviour, git cliff will just omit generating changelog entry all together. And so generated changelog has gaps:  v2.1.0 => v2.3.0.

**Comment by AlecRust** [comment]
Wondering if this should be reopened as a bug or request? I've bumped into this too and the behavior is somewhat unexpected.

It would be nice to be able to handle this in the template e.g.

```
[changelog]
# Changelog body in Slack's "mrkdwn" format
# https://keats.github.io/tera/docs/#introduction
# https://api.slack.com/reference/surfaces/formatting
body = """
{% set has_commits = false %}\
{% for group, commits in commits | group_by(attribute="group") %}\
	{% set has_commits = true %}\
	*{{ group | striptags | trim | upper_first }}*\n\n\
	{% for commit in commits %}\
		• {% if commit.scope %}*({{ commit.scope }})* {% endif %}{{ commit.message | upper_first | trim }}\
		{% if commit.github.pr_number %} \
			(<{{ self::remote_url() }}/pull/{{ commit.github.pr_number }}|#{{ commit.github.pr_number }}>)\
		{% else %} \
			(<{{ self::remote_url() }}/commit/{{ commit.id }}|{{ commit.id | truncate(length=7, end="") }}>)\
		{% endif %}\n\
	{% endfor %}{% if not loop.last %}\n{% endif %}
{% endfor %}\
{% if not has_commits %}Bug fixes and improvements 😉{% endif %}\
{%- macro remote_url() -%}
	https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}
"""
```

But as you say, git-cliff skips all together in this case.

**Comment by orhun** [comment]
@AlecRust sorry for the late reply, are you still having the same problem? I'm happy to discuss it in a new issue 🐻
