### ISSUE TITLE
The default config treats any string with `ci` characters in it as a `ci: ` commit message

### ISSUE THREAD

**Issue by ravenexp** [orhun/git-cliff#519]
**Describe the bug**

The default `cliff.toml` contains the following line:

```
  { message = "^chore|ci", group = "<!-- 7 -->⚙️ Miscellaneous Tasks" },
```

The message regex matches either a string starting with `"chore"` _or_ any string with `"ci"` in it since `|` has the lowest precedence.

**To reproduce**

1. `git cliff --init`
2. `git init ; git add cliff.toml`
3. `git commit -m "acidic: what?"`
4. `git cliff`

**Expected behavior**

The non-standard commit message is not matched by the "Miscellaneous Tasks" group.

**Screenshots / Logs**

# Changelog

All notable changes to this project will be documented in this file.

### ⚙️  Miscellaneous Tasks

- What?

**Software information**

- Project version: 2.0.4

**Extra thoughts**

It's just my personal preference, but I think `ci: blah blah ...` messages should go into their own group.

**Comment by orhun** [comment]
Hey, this should be fixed in 110b9b8d2676800ebe169287fa5d2a93c9f6b55f - thanks a lot for reporting! 🐻
