### ISSUE TITLE
Does not work `message` and `body` in `commit_parsers`

### ISSUE THREAD

**Issue by hituzi-no-sippo** [orhun/git-cliff#53]
**Describe the bug**

`commit_parsers.message` includes body in the search range.
Similarly, `commit_parsers.body` includes message in the search range.

**To Reproduce**

1. Create git repository.
1. Create git-cliff configuration file.
1. Change git-cliff configuration.
1. Create commits.
1. Run `git cliff`.
   Output not as expected.

Details about the commit log, `commit_parses`, output CHANGELOG, etc. are described in "Screenshots/Logs".

**Expected behavior**

The search range of `commit_parsers.message` is message only.
The search range of `commit_parsers.body` is body only.

**Screenshots/Logs**

**cliff.toml**

```toml
[git]
conventional_commits = false
filter_unconventional = false
commit_parsers = [
    { message = "apple", group = "Apple"},
    { body = "banana", group = "Banana"},
]
```

The other values are default values.

**git log**

```
commit 469fba85058e6103ac1b892e4edde951f545ee0e (HEAD -> main)
Author: hituzi_no_sippo <dev@hituzi-no-sippo.me>
Date:   Sun Jan 30 15:46:21 2022 +0900

    banana

commit 61f0ea6765b321c7d23a7b2c31ed191c37dfbea3
Author: hituzi_no_sippo <dev@hituzi-no-sippo.me>
Date:   Sun Jan 30 15:45:54 2022 +0900

    camel

    apple

commit 3a819db2bdb0917d3864998dab5858afc8fc8da2
Author: hituzi_no_sippo <dev@hituzi-no-sippo.me>
Date:   Sun Jan 30 15:45:06 2022 +0900

    apple
```

**git cliff**

```
# Changelog
All notable changes to this project will be documented in this file.

## [unreleased]

### Apple

- Apple

- Camel

apple


### Banana

- Banana


<!-- generated by git-cliff -->
```

There is no apple in the message of the Camel, but it is listed in CHANGELOG.
There is no banana in the body of the Banana, but it is listed in CHANGELOG.

**Expected**

```
# Changelog
All notable changes to this project will be documented in this file.

## [unreleased]

### Apple

- Apple


<!-- generated by git-cliff -->
```

**System (please complete the following information):**

- OS Ubuntu 20.04 LTS (WSL2)
- Project Version: [2be04f8b2214513d08d349b254a97a8c783073fb](https://github.com/orhun/git-cliff/commit/2be04f8b2214513d08d349b254a97a8c783073fb)

**Additional context**

Code that may be relevant
https://github.com/orhun/git-cliff/blob/848d8a587efd5f611a98b647b954c06938fac24a/git-cliff-core/src/commit.rs#L115-L120

Thank you.

**Comment by orhun** [comment]
> **Describe the bug**
> 
> `commit_parsers.message` includes body in the search range. Similarly, `commit_parsers.body` includes message in the search range.
> 
> **To Reproduce**
> 
>     1. Create git repository.
> 
>     2. Create git-cliff configuration file.
> 
>     3. Change git-cliff configuration.
> 
>     4. Create commits.
> 
>     5. Run `git cliff`.
>        Output not as expected.
> 
> 
> Details about the commit log, `commit_parses`, output CHANGELOG, etc. are described in "Screenshots/Logs".
> 
> **Expected behavior**
> 
> The search range of `commit_parsers.message` is message only. The search range of `commit_parsers.body` is body only.
> 
> **Screenshots/Logs**
> 
> **cliff.toml**
> 
> ```toml
> [git]
> conventional_commits = false
> filter_unconventional = false
> commit_parsers = [
>     { message = "apple", group = "Apple"},
>     { body = "banana", group = "Banana"},
> ]
> ```
> 
> The other values are default values.
> 
> **git log**
> 
> ```
> commit 469fba85058e6103ac1b892e4edde951f545ee0e (HEAD -> main)
> Author: hituzi_no_sippo <dev@hituzi-no-sippo.me>
> Date:   Sun Jan 30 15:46:21 2022 +0900
> 
>     banana
> 
> commit 61f0ea6765b321c7d23a7b2c31ed191c37dfbea3
> Author: hituzi_no_sippo <dev@hituzi-no-sippo.me>
> Date:   Sun Jan 30 15:45:54 2022 +0900
> 
>     camel
> 
>     apple
> 
> commit 3a819db2bdb0917d3864998dab5858afc8fc8da2
> Author: hituzi_no_sippo <dev@hituzi-no-sippo.me>
> Date:   Sun Jan 30 15:45:06 2022 +0900
> 
>     apple
> ```
> 
> **git cliff**
> 
> ```
> # Changelog
> All notable changes to this project will be documented in this file.
> 
> ## [unreleased]
> 
> ### Apple
> 
> - Apple
> 
> - Camel
> 
> apple
> 
> 
> ### Banana
> 
> - Banana
> 
> 
> 
> ```
> 
> There is no apple in the message of the Camel, but it is listed in CHANGELOG. There is no banana in the body of the Banana, but it is listed in CHANGELOG.
> 
> **Expected**
> 
> ```
> # Changelog
> All notable changes to this project will be documented in this file.
> 
> ## [unreleased]
> 
> ### Apple
> 
> - Apple
> 
> 
> 
> ```
> 
> **System (please complete the following information):**
> 
>     * OS Ubuntu 20.04 LTS (WSL2)
> 
>     * Project Version: [2be04f8b2214513d08d349b254a97a8c783073fb](https://github.com/orhun/git-cliff/commit/2be04f8b2214513d08d349b254a97a8c783073fb)
> 
> 
> **Additional context**
> 
> Code that may be relevant
> 
> https://github.com/orhun/git-cliff/blob/848d8a587efd5f611a98b647b954c06938fac24a/git-cliff-core/src/commit.rs#L115-L120
> 
> Thank you.


Hello. Unfortunately, this is not possible.

**Comment by orhun** [comment]
Hello! Unfortunately, this is not possible due to `conventional_commits` being set to `false`. When you specify this, `git-cliff` cannot differentiate between "message" and "body". See the [context](https://github.com/orhun/git-cliff#non-conventional-commits) for non-conventional commits.

**Comment by orhun** [comment]
However, I pushed e1da61150f07f641dfe471e240033e13cc19d089 which means you can now achieve this with conventional commits.

`git log`:

```
commit 1121b3d2ba38486357fd3bc9d7aca966f3e29ea8
Author: Orhun Parmaksız <orhunparmaksiz@gmail.com>
Date:   Sat Feb 5 15:56:15 2022 +0300

    feat: banana

commit 834a6dde62863086d9c16b2acd2c45204f39ca3d
Author: Orhun Parmaksız <orhunparmaksiz@gmail.com>
Date:   Sat Feb 5 15:56:10 2022 +0300

    feat: camel
    
    apple

commit 1ffbf40bcf9102cb5c83bb32b7016dd26438932b
Author: Orhun Parmaksız <orhunparmaksiz@gmail.com>
Date:   Sat Feb 5 15:55:46 2022 +0300

    feat: apple
```

`cliff.toml`:

```toml
conventional_commits = true
filter_unconventional = true
commit_parsers = [
    { message = "feat: apple", group = "Apple"},
    { body = "banana", group = "Banana"},
]
filter_commits = true
```

Changelog result:

```
# Changelog
All notable changes to this project will be documented in this file.

## [unreleased]

### Apple

- Apple

<!-- generated by git-cliff -->
```

**Comment by hituzi-no-sippo** [comment]
> See the [context](https://github.com/orhun/git-cliff#non-conventional-commits) for non-conventional commits.

Oh, I missed that.

> However, I pushed https://github.com/orhun/git-cliff/commit/e1da61150f07f641dfe471e240033e13cc19d089 which means you can now achieve this with conventional commits.

Good job 👍

I've checked.
Thank you 😄
