### ISSUE TITLE
--bumped-version return whole changelog if nothing to bump

### ISSUE THREAD

**Issue by liuyinz** [orhun/git-cliff#533]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

If there is no unreleased commits, `git-cliff --bumped-version` would return whole changelog content, which is not the result expected.

I think option `--bumped-version` should return new version if exists, or return current latest version as default.

### Steps To Reproduce

1. checkout on newest tag
2. run `git-cliff --bumnped-version`

### Expected behavior

return latest tag if no unreleased commits rather than whole changelog content

### Software information

- Operating system:
- Rust version:
- Project version:

**Comment by orhun** [comment]
Thanks for reporting! This should be fixed in 45c87f2f307e8441c128b81835b662362e6b380a
