### ISSUE TITLE
BadZipFile error while installing via pip

### ISSUE THREAD

**Issue by karl0ss** [orhun/git-cliff#534]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

Unable to install git-cliff via pip

### Steps To Reproduce

Brand new python venv 
```
❯ python -m venv venv
❯ venv/Scripts/activate
❯ pip install setuptools wheel
Requirement already satisfied: setuptools in c:\users\karl.hudgell\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages (63.2.0)
Requirement already satisfied: wheel in c:\users\karl.hudgell\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages (0.37.1)

[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip
❯ python.exe -m pip install --upgrade pip

zsh: command not found: python.exe
❯ python -m pip install --upgrade pip

Requirement already satisfied: pip in c:\users\karl.hudgell\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages (23.3.2)
Collecting pip
  Downloading pip-24.0-py3-none-any.whl.metadata (3.6 kB)
Downloading pip-24.0-py3-none-any.whl (2.1 MB)
   ---------------------------------------- 2.1/2.1 MB 33.9 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 23.3.2
    Uninstalling pip-23.3.2:
      Successfully uninstalled pip-23.3.2
Successfully installed pip-24.0
```

### Expected behavior

Git-Cliff should install

### Screenshots / Logs

```
❯ pip install git-cliff
Collecting git-cliff
  Downloading git_cliff-2.1.2-py3-none-win_amd64.whl.metadata (6.1 kB)
Downloading git_cliff-2.1.2-py3-none-win_amd64.whl (6.4 MB)
   ---------------------------------------- 6.4/6.4 MB 14.1 MB/s eta 0:00:00
Installing collected packages: git-cliff
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\Karl.Hudgell\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Users\Karl.Hudgell\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages\pip\_internal\cli\req_command.py", line 245, in wrapper
    return func(self, options, args)
  File "C:\Users\Karl.Hudgell\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages\pip\_internal\commands\install.py", line 452, in run
    installed = install_given_reqs(
  File "C:\Users\Karl.Hudgell\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages\pip\_internal\req\__init__.py", line 72, in install_given_reqs
    requirement.install(
  File "C:\Users\Karl.Hudgell\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages\pip\_internal\req\req_install.py", line 856, in install
    install_wheel(
  File "C:\Users\Karl.Hudgell\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages\pip\_internal\operations\install\wheel.py", line 725, in install_wheel
    _install_wheel(
  File "C:\Users\Karl.Hudgell\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages\pip\_internal\operations\install\wheel.py", line 585, in _install_wheel
    file.save()
  File "C:\Users\Karl.Hudgell\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages\pip\_internal\operations\install\wheel.py", line 398, in save
    self._file.save()
  File "C:\Users\Karl.Hudgell\.pyenv\pyenv-win\versions\3.10.6\lib\site-packages\pip\_internal\operations\install\wheel.py", line 384, in save
    shutil.copyfileobj(f, dest)
  File "C:\Users\Karl.Hudgell\.pyenv\pyenv-win\versions\3.10.6\lib\shutil.py", line 195, in copyfileobj
    buf = fsrc_read(length)
  File "C:\Users\Karl.Hudgell\.pyenv\pyenv-win\versions\3.10.6\lib\zipfile.py", line 925, in read
    data = self._read1(n)
  File "C:\Users\Karl.Hudgell\.pyenv\pyenv-win\versions\3.10.6\lib\zipfile.py", line 1015, in _read1
    self._update_crc(data)
  File "C:\Users\Karl.Hudgell\.pyenv\pyenv-win\versions\3.10.6\lib\zipfile.py", line 943, in _update_crc
    raise BadZipFile("Bad CRC-32 for file %r" % self.name)
zipfile.BadZipFile: Bad CRC-32 for file 'git_cliff-2.1.2.data/scripts/git-cliff-completions.exe'
```

### Software information

- Operating system: Windows 10
- Rust version: NA
- Project version: NA
- Python version: 3.10.6

**Comment by karl0ss** [comment]
Have tried 2.1.2 and 2.1.1 both ```zipfile.BadZipFile: Bad CRC-32 for file 'git_cliff-2.1.1.data/scripts/git-cliff-completions.exe'```

Have also tried 2.0.4 ```zlib.error: Error -3 while decompressing data: invalid literal/length code```

**Comment by karl0ss** [comment]
Also got a collegue who has tried on his windows machine and he gets the same 
```
ERROR: Exception:
Traceback (most recent call last):
  File "c:\users\alex.reed\git\test-git-cliff\.venv\lib\site-packages\pip\_internal\cli\base_command.py", line 180, in _main
    status = self.run(options, args)
  File "c:\users\alex.reed\git\test-git-cliff\.venv\lib\site-packages\pip\_internal\cli\req_command.py", line 204, in wrapper
    return func(self, options, args)
  File "c:\users\alex.reed\git\test-git-cliff\.venv\lib\site-packages\pip\_internal\commands\install.py", line 393, in run
    installed = install_given_reqs(
  File "c:\users\alex.reed\git\test-git-cliff\.venv\lib\site-packages\pip\_internal\req\__init__.py", line 77, in install_given_reqs
    requirement.install(
  File "c:\users\alex.reed\git\test-git-cliff\.venv\lib\site-packages\pip\_internal\req\req_install.py", line 782, in install
    install_wheel(
  File "c:\users\alex.reed\git\test-git-cliff\.venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 810, in install_wheel
    _install_wheel(
  File "c:\users\alex.reed\git\test-git-cliff\.venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 653, in _install_wheel
    file.save()
  File "c:\users\alex.reed\git\test-git-cliff\.venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 436, in save
    self._file.save()
  File "c:\users\alex.reed\git\test-git-cliff\.venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 420, in save
    shutil.copyfileobj(f, dest)
  File "C:\Users\alex.reed\.pyenv\pyenv-win\versions\3.8.10\lib\shutil.py", line 205, in copyfileobj
    buf = fsrc_read(length)
  File "C:\Users\alex.reed\.pyenv\pyenv-win\versions\3.8.10\lib\zipfile.py", line 940, in read
    data = self._read1(n)
  File "C:\Users\alex.reed\.pyenv\pyenv-win\versions\3.8.10\lib\zipfile.py", line 1030, in _read1
    self._update_crc(data)
  File "C:\Users\alex.reed\.pyenv\pyenv-win\versions\3.8.10\lib\zipfile.py", line 958, in _update_crc
    raise BadZipFile("Bad CRC-32 for file %r" % self.name)
zipfile.BadZipFile: Bad CRC-32 for file 'git_cliff-2.1.2.data/scripts/git-cliff-completions.exe'
```

**Comment by karl0ss** [comment]
Another collegue has tried on this mac (still python 3.10.6) and it installs fine, so this seems to only be a windows issue..

**Comment by karl0ss** [comment]
Also seems to install fine on windows under WSL (Ubuntu) but not natively

**Comment by karl0ss** [comment]
Also, I have manually downloaded the whl from pypi this morning and tried to isntall that, same issue 
```
(venv) C:\Users\Karl.Hudgell\Documents\Work\HE\git-cliff>dir
 Volume in drive C is OS
 Volume Serial Number is 686F-B344

 Directory of C:\Users\Karl.Hudgell\Documents\Work\HE\git-cliff

05/03/2024  10:02    <DIR>          .
05/03/2024  10:02    <DIR>          ..
05/03/2024  10:01         6,398,708 git_cliff-2.1.2-py3-none-win_amd64.whl
05/03/2024  08:27    <DIR>          venv
               1 File(s)      6,398,708 bytes
               3 Dir(s)  173,182,754,816 bytes free

(venv) C:\Users\Karl.Hudgell\Documents\Work\HE\git-cliff>pip install git_cliff-2.1.2-py3-none-win_amd64.whl
Processing c:\users\karl.hudgell\documents\work\he\git-cliff\git_cliff-2.1.2-py3-none-win_amd64.whl
Installing collected packages: git-cliff
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\Karl.Hudgell\Documents\Work\HE\git-cliff\venv\lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Users\Karl.Hudgell\Documents\Work\HE\git-cliff\venv\lib\site-packages\pip\_internal\cli\req_command.py", line 245, in wrapper
    return func(self, options, args)
  File "C:\Users\Karl.Hudgell\Documents\Work\HE\git-cliff\venv\lib\site-packages\pip\_internal\commands\install.py", line 452, in run
    installed = install_given_reqs(
  File "C:\Users\Karl.Hudgell\Documents\Work\HE\git-cliff\venv\lib\site-packages\pip\_internal\req\__init__.py", line 72, in install_given_reqs
    requirement.install(
  File "C:\Users\Karl.Hudgell\Documents\Work\HE\git-cliff\venv\lib\site-packages\pip\_internal\req\req_install.py", line 856, in install
    install_wheel(
  File "C:\Users\Karl.Hudgell\Documents\Work\HE\git-cliff\venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 725, in install_wheel
    _install_wheel(
  File "C:\Users\Karl.Hudgell\Documents\Work\HE\git-cliff\venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 585, in _install_wheel
    file.save()
  File "C:\Users\Karl.Hudgell\Documents\Work\HE\git-cliff\venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 398, in save
    self._file.save()
  File "C:\Users\Karl.Hudgell\Documents\Work\HE\git-cliff\venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 384, in save
    shutil.copyfileobj(f, dest)
  File "C:\Users\Karl.Hudgell\.pyenv\pyenv-win\versions\3.10.6\lib\shutil.py", line 195, in copyfileobj
    buf = fsrc_read(length)
  File "C:\Users\Karl.Hudgell\.pyenv\pyenv-win\versions\3.10.6\lib\zipfile.py", line 925, in read
    data = self._read1(n)
  File "C:\Users\Karl.Hudgell\.pyenv\pyenv-win\versions\3.10.6\lib\zipfile.py", line 1015, in _read1
    self._update_crc(data)
  File "C:\Users\Karl.Hudgell\.pyenv\pyenv-win\versions\3.10.6\lib\zipfile.py", line 943, in _update_crc
    raise BadZipFile("Bad CRC-32 for file %r" % self.name)
zipfile.BadZipFile: Bad CRC-32 for file 'git_cliff-2.1.2.data/scripts/git-cliff-completions.exe'

(venv) C:\Users\Karl.Hudgell\Documents\Work\HE\git-cliff>
```

**Comment by karl0ss** [comment]
I have downloaded the zip fro pypi and tried to extract it using peazip, and I still et an error on that file, are we sure the published package for win/amd64 isn't broken? 

![image](https://github.com/orhun/git-cliff/assets/2493260/34b7c26a-4ccf-4bbf-9a29-e3dc110be1d0)

**Comment by karl0ss** [comment]
I was able to install this globally using ```winget install --id=orhun.git-cliff  -e``` not sure why it wont install/work by Pypi

**Comment by orhun** [comment]
Hey, thanks for sharing your findings!

I would like to ping @radusuciu who authored the PyPI workflow for installing via pip. Maybe he knows something.

I'm curious about how did you get the zip file for Windows. I tried `pip download` but it didn't gave me that exact file. I also would like to test that out locally in case it hints what's wrong. But my number 1 suspicion is that something is going on with [maturin](https://github.com/PyO3/maturin) - I'm not sure though.

**Comment by radusuciu** [comment]
you rang?

I can take a look. I've been using the pypi package in a few projects without issues but it's all been Linux or WSL. I would also suspect that maturin might be involved..

**Comment by radusuciu** [comment]
I can confirm that this happens on Windows 10 with Python 3.11.8 and will add that `git-cliff` installs fine for every version up until 2.0.2.

**Comment by orhun** [comment]
> I can confirm that this happens on Windows 10 with Python 3.11.8 and will add that git-cliff installs fine for every version up until 2.0.2.

That's weird, there were no significant changes between those versions.

But maybe something changed in maturin? 👀

**Comment by radusuciu** [comment]
Guessing this is the culprit: https://github.com/orhun/git-cliff/blob/16bea5179a89af26dd0bfb07c7d6b7d1efa3c54e/pypi/pyproject.toml#L2

I was way too specific in pinning this version of maturin. There's been a 1.0 release since then so I'm going to test locally if this creates an installable wheel.

**Comment by radusuciu** [comment]
Alright, so unfortunately it's not so simple. I installed the same version of maturin (0.14.7) on my Windows 10 workstation and was able to build (`maturin build --release --sdist --out wheels --target x86_64-pc-windows-msvc`) and install the wheel with zero issues.

**Comment by orhun** [comment]
I see, should we expect it to be fixed after #539?

**Comment by karl0ss** [comment]
Glad this has helped, I would much prefer to install via the project deps than have to have people install on their mac/win using wget/brew...

@orhun I just downloaded the wheel file manually via the pypi webpage and tried to install using pip add "pathtowheel" and the whl can be opened in any zip program, i used peazip, but you gett he same crc issue...

glad it looks like this might go soemwehre and get fixed, thanks for your help guys..

**Comment by radusuciu** [comment]
> I see, should we expect it to be fixed after #539?

I'm not 100% since I could not reproduce the failure locally, but I did verify that the wheels generated in my hacked (removed a few irrelevant jobs) fork are installable on my Windows computer.

Relevant job: https://github.com/radusuciu/git-cliff/actions/runs/8182476507/job/22373882202
Wheel artifact: https://github.com/radusuciu/git-cliff/actions/runs/8182476507/artifacts/1304538766

To avoid this problem in the future, it might be good to build wheels during CI and test whether they can be installed at least. Alternatively it could be added as another CD step during the pre-release process.

**Comment by radusuciu** [comment]
> I think it is a good idea to build wheels during CI to make sure everything works before creating a release. Are you possibly interested in making a PR? 🐻

yes I can give it a shot. Two questions:
1. Are you okay with some duplication between the CI and CD workflows? I'm not that familiar with reusable workflows (or other reuse mechanisms available in GHA) so that might be a higher bar for me.
2. Do you want the wheel building and testing implemented in `ci.yml` or a separate workflow?

**Comment by orhun** [comment]
I think duplication is fine - let's have the basic checks and then we can worry about refactoring it 🐻 

Yup, we can place it in `ci.yml`.

**Comment by karl0ss** [comment]
@radusuciu I have downloaded and tested your artifact this morning and all seems to be well...

I used poetry and tried to install using that and did...get and error...
```
> poetry add .\wheels-x86_64-pc-windows-msvc\git_cliff-2.1.6-py3-none-win_amd64.whl

Unable to create package with no name
```

But then tried with pip in my poetry env and it worked ok.

```
> pip install .\wheels-x86_64-pc-windows-msvc\git_cliff-2.1.6-py3-none-win_amd64.whl
Processing \wheels-x86_64-pc-windows-msvc\git_cliff-2.1.6-py3-none-win_amd64.whl
Installing collected packages: git-cliff
Successfully installed git-cliff-2.1.6
```

And was able to build changelog, so def progress, I will have a play today and see if I can understand why poetry couldn't install, as I quite often install direct from wheels and it works fine..

thanks for your help/work

**Comment by radusuciu** [comment]
> @radusuciu I have downloaded and tested your artifact this morning and all seems to be well...
> 
> 
> 
> I used poetry and tried to install using that and did...get and error...
> 
> ```
> 
> > poetry add .\wheels-x86_64-pc-windows-msvc\git_cliff-2.1.6-py3-none-win_amd64.whl
> 
> 
> 
> Unable to create package with no name
> 
> ```
> 
> 
> 
> But then tried with pip in my poetry env and it worked ok.
> 
> 
> 
> ```
> 
> > pip install .\wheels-x86_64-pc-windows-msvc\git_cliff-2.1.6-py3-none-win_amd64.whl
> 
> Processing \wheels-x86_64-pc-windows-msvc\git_cliff-2.1.6-py3-none-win_amd64.whl
> 
> Installing collected packages: git-cliff
> 
> Successfully installed git-cliff-2.1.6
> 
> ```
> 
> 
> 
> And was able to build changelog, so def progress, I will have a play today and see if I can understand why poetry couldn't install, as I quite often install direct from wheels and it works fine..
> 
> 
> 
> thanks for your help/work

I think I know the error here and can test this afternoon.

Thanks for the feedback!

**Comment by karl0ss** [comment]
@radusuciu I spoke with the poetry team today, and i'm not sure its your issue, they stated "the issue is that the pkginfo version that is installed does not support metadata version 2.3"

They gave me a command to upadte pkginfo in my pipx env to test, but I wont get around to trying that on monday, I also see they pushed the upversioned dep onto main today, so I guess it will be officially supported in coming poetry version.

**Comment by radusuciu** [comment]
> @radusuciu I spoke with the poetry team today, and i'm not sure its your issue, they stated "the issue is that the pkginfo version that is installed does not support metadata version 2.3"
> 
> They gave me a command to upadte pkginfo in my pipx env to test, but I wont get around to trying that on monday, I also see they pushed the upversioned dep onto main today, so I guess it will be officially supported in coming poetry version. [python-poetry/poetry#9130](https://github.com/python-poetry/poetry/pull/9130)

I guess I must have a different version of pkginfo since I'm testing on 3.11?

If there's something we can tweak in the `pyproject.toml` for git-cliff then I think that'd be worthwhile to avoid this issue for users that might not be using the most up to date poetry.

**Comment by karl0ss** [comment]
I'm not 100% on that, but if the wheel gets published, I can try install it and see if it works, if not then it looks like updating as they said would work, or using the latest with 3.11 would work as you said..thanks for looking into all of this..

**Comment by radusuciu** [comment]
Looks like the metadata-version was bumped to 2.3 as of maturin 1.5.0: https://github.com/PyO3/maturin/pull/1965

Comparing the METADATA file from the 2.1.2 wheel on PIP and the workflow wheel above, it seems like everything is the same except for the `Metadata-Version` field, so I'm not sure we can avoid this without pinning maturin to 1.4.0, but this is a bit deeper in the packaging rabbit hole than I'm used to.

**Comment by karl0ss** [comment]
Looks like 1.8.2 poetry supports the latest wheels, can we get them published to Pypi?

**Comment by karl0ss** [comment]
Any idea/update on when we can get this on Pypi so can be consumed?

**Comment by orhun** [comment]
Yup, I can probably release a minor version pretty soon.

**Comment by orhun** [comment]
I created RC release on Test PyPi - @karl0ss can you test it if you have the chance? I think I will create `v2.2.0` tomorrow.

**Comment by orhun** [comment]
Looks like the Maturin workflow failed: <https://github.com/orhun/git-cliff/actions/runs/8412795467/job/23034491981>

```
🎛️ Running in non-interactive mode on CI
🚀 Uploading 10 packages
💥 maturin failed
  Caused by: 💥 Failed to upload "git_cliff-2.2.0rc1.tar.gz" (60.4 KB)
  Caused by: Could not read the metadata from the package at /home/runner/work/git-cliff/git-cliff/pypi/wheels/git_cliff-2.2.0rc1.tar.gz
  Caused by: archive header checksum mismatch
```

@radusuciu can you take a look?

**Comment by radusuciu** [comment]
Odd.. I just got back from a trip but I'll review the log after work and let you know.

**Comment by orhun** [comment]
I looked into this last night but couldn't figure out what happened. FWIW we can download the artifacts from the latest `cd` run, I inspected them to only find out everything looks good :/

**Comment by radusuciu** [comment]
I took a look as well and nothing stands out. I have also verified that the wheel is installable on my Windows system so that's good at least.

I'll attempt to debug the publishing issue in a fork.

**Comment by orhun** [comment]
Thank you! 🙏🏼 It's the only thing that's blocking the release rn.

**Comment by radusuciu** [comment]
So my release [worked](https://github.com/radusuciu/git-cliff/actions/runs/8471468911). [Here it is on TestPyPi](https://test.pypi.org/project/test-pypi-deploy-git-cliff/#history). Please ignore the version number, that's just a result of me hacking at it until I could push it through.

Things I chopped off include: NPM, deb, RPM, cargo, and homebrew publishing.. but perhaps most relevant given the `checksum mismatch` error is the fact that I removed the signing. See [this diff](https://github.com/orhun/git-cliff/compare/main...radusuciu:git-cliff:main?diff=split&w=#diff-ea3ea8c9932adc7ba8161ceda844fedd43b006848ef1140c050cbd7ea0788a18), focusing on changes to `cd.yaml` -- other changes shouldn't matter (I accidentally based this on another branch).

Needs a bit more thought here.

Btw, I might suggest skipping the pypi release for v2.2.0 if you just want to get the release out. We can catch up again on 2.2.1

**Comment by orhun** [comment]
Hmm, weird. Normally signing shouldn't affect the PyPI release but maybe there is some hidden magic going on somewhere.

I will release another RC for testing it again and if it doesn't work then I think I will just disable PyPI releases until we figure things out.

Thanks for debugging it!

**Comment by radusuciu** [comment]
To confirm my guess, I could add back that step (setting the necessary secrets) and verify that the pypi publish step fails, and then we can go from there.

**Comment by orhun** [comment]
Sounds good, let's do that

**Comment by orhun** [comment]
Created `v2.2.0` with no issues now, not sure what was wrong before. 🤷🏼‍♂️ 

@karl0ss can you test the latest version from PyPI and see if the error still happens?

**Comment by radusuciu** [comment]
Oh no, a heisenbug!

**Comment by karl0ss** [comment]
Have just spun up windows sandbox, installed python 3.10.6 (without using pyenv) and installed poetry using pipx as suggested...but still the same issue

![image](https://github.com/orhun/git-cliff/assets/2493260/86433954-04e2-4659-9b68-cd15f33bd102)

**Comment by radusuciu** [comment]
@karl0ss can you confirm that you get the issue just with `pip` in the same environment?

**Comment by karl0ss** [comment]
Clean windows 10 sandbox, python 3.10.6 installed officially via the installer, git installed via official installer, no poetry installed...

![image](https://github.com/orhun/git-cliff/assets/2493260/c1b99bf4-0ecd-44b1-a12e-c34f84086bf4)

Same issue...

**Comment by DeadNews** [comment]
https://github.com/orhun/git-cliff/actions/runs/8491060435

![Screenshot_%d](https://github.com/orhun/git-cliff/assets/8158661/959268e2-449f-467d-b0bf-b77baee3fae0)

The `git_cliff-2.2.0-py3-none-win_amd64.whl` in these archives are valid.

I don't know where `wheels-x86_64-pc-windows-gnu` is used.
The version on `pypi` is `wheels-x86_64-pc-windows-msvc` with corrupted `git-cliff-completions.exe`.


```console
$ find . -type f -exec sha256sum {} 

201db433a945a7502cf4f6e487044c1dae911336e55babd0d02147483851fd6a  ./pypi/git_cliff-2.2.0.dist-info/METADATA
e0d67ecd3747a0f9fadeeff14da771270862326289eeb949f6772e96aea7efe6  ./pypi/git_cliff-2.2.0.dist-info/WHEEL
8f1c58ea8c9a3f5cccd171beac989de62da7e11c2137107a9ab34d2e2ac02c6c  ./pypi/git_cliff-2.2.0.dist-info/RECORD
711fd3a58f36221c9f633e3b50efdfc6c102bdc9d1524d3c2575e505d57b12ba  ./pypi/git_cliff-2.2.0.data/scripts/git-cliff-completions.exe
dca0f554e1010708963d3a4e0c71f196639d3376c68cda62cf8286fe3195ab45  ./pypi/git_cliff-2.2.0.data/scripts/git-cliff-mangen.exe
5fec7ed499486e433c889efd55e8d3b748301cc4a966e1501acdb5e1d05ea8ac  ./pypi/git_cliff-2.2.0.data/scripts/git-cliff.exe

201db433a945a7502cf4f6e487044c1dae911336e55babd0d02147483851fd6a  ./wheels-x86_64-pc-windows-msvc/git_cliff-2.2.0.dist-info/METADATA
e0d67ecd3747a0f9fadeeff14da771270862326289eeb949f6772e96aea7efe6  ./wheels-x86_64-pc-windows-msvc/git_cliff-2.2.0.dist-info/WHEEL
8f1c58ea8c9a3f5cccd171beac989de62da7e11c2137107a9ab34d2e2ac02c6c  ./wheels-x86_64-pc-windows-msvc/git_cliff-2.2.0.dist-info/RECORD
2a811de078807e000a1494914178c7565641f5e2ecacb58bdf3d8c0ab60bfcbe  ./wheels-x86_64-pc-windows-msvc/git_cliff-2.2.0.data/scripts/git-cliff-completions.exe
dca0f554e1010708963d3a4e0c71f196639d3376c68cda62cf8286fe3195ab45  ./wheels-x86_64-pc-windows-msvc/git_cliff-2.2.0.data/scripts/git-cliff-mangen.exe
5fec7ed499486e433c889efd55e8d3b748301cc4a966e1501acdb5e1d05ea8ac  ./wheels-x86_64-pc-windows-msvc/git_cliff-2.2.0.data/scripts/git-cliff.exe

201db433a945a7502cf4f6e487044c1dae911336e55babd0d02147483851fd6a  ./wheels-x86_64-pc-windows-gnu/git_cliff-2.2.0.dist-info/METADATA
e0d67ecd3747a0f9fadeeff14da771270862326289eeb949f6772e96aea7efe6  ./wheels-x86_64-pc-windows-gnu/git_cliff-2.2.0.dist-info/WHEEL
b363d8db7f68b5f65f0a63fdbe781fa6cb4a3a5cc5cbfb026df3ba6bf3f857a0  ./wheels-x86_64-pc-windows-gnu/git_cliff-2.2.0.dist-info/RECORD
e95816287d3eed917e14f1ad480edbf87a8612b5a0f5459e7e03bcd231d60d6f  ./wheels-x86_64-pc-windows-gnu/git_cliff-2.2.0.data/scripts/git-cliff-completions.exe
712c5c05b72fa3b5fc996cc31b1bcf8714292cb8b50afb7a24c9da16b136485b  ./wheels-x86_64-pc-windows-gnu/git_cliff-2.2.0.data/scripts/git-cliff-mangen.exe
5bdf95d64be282af3d1935fadd6687e62f6a52ed73545eb2c290484d40338895  ./wheels-x86_64-pc-windows-gnu/git_cliff-2.2.0.data/scripts/git-cliff.exe
```

```diff
--- a/pypi
+++ b/wheels-x86_64-pc-windows-msvc
@@ -1,6 +1,6 @@
 201db433a945a7502cf4f6e487044c1dae911336e55babd0d02147483851fd6a  ./git_cliff-2.2.0.dist-info/METADATA
 e0d67ecd3747a0f9fadeeff14da771270862326289eeb949f6772e96aea7efe6  ./git_cliff-2.2.0.dist-info/WHEEL
 8f1c58ea8c9a3f5cccd171beac989de62da7e11c2137107a9ab34d2e2ac02c6c  ./git_cliff-2.2.0.dist-info/RECORD
-711fd3a58f36221c9f633e3b50efdfc6c102bdc9d1524d3c2575e505d57b12ba  ./git_cliff-2.2.0.data/scripts/git-cliff-completions.exe
+2a811de078807e000a1494914178c7565641f5e2ecacb58bdf3d8c0ab60bfcbe  ./git_cliff-2.2.0.data/scripts/git-cliff-completions.exe
 dca0f554e1010708963d3a4e0c71f196639d3376c68cda62cf8286fe3195ab45  ./git_cliff-2.2.0.data/scripts/git-cliff-mangen.exe
 5fec7ed499486e433c889efd55e8d3b748301cc4a966e1501acdb5e1d05ea8ac  ./git_cliff-2.2.0.data/scripts/git-cliff.exe
```

Apparently the error is somewhere at the [Publish PyPI package](https://github.com/orhun/git-cliff/ctions/runs/8491060435/job/23262960359) stage.

https://github.com/orhun/git-cliff/blob/98647800565f588f656234f5b717d3ce35db3344/.github/workflows/cd.yml#L321-L338

I can only [note](https://github.com/orhun/git-cliff/actions/runs/8491060435/job/23262960359#step:2:49) that `git_cliff-2.2.0-py3-none-win_amd64.whl` is extracted from `wheels-x86_64-pc-windows-gnu` and `wheels-x86_64-pc-windows-msvc`. Apparently, the latter (`msvc`) overwrites the former.

![Screenshot_%d-2](https://github.com/orhun/git-cliff/assets/8158661/67e6bad6-969e-4e5e-8588-80b971b6a6d6)

**Comment by radusuciu** [comment]
Great analysis @DeadNews. Is this the only such collision that you saw?

Here are two proposed solutions:
1. Set `PYPI_PUBLISH` for the  `x86_64-pc-windows-gnu` platform to `false`
2. Ensure that the `msvc` and `gnu` wheels get a different name.

@orhun, does having `mingw` and `msvc` compiled versions on PyPI serve an important purpose?

**Comment by orhun** [comment]
Nope, not really. Those are there for the sake of "supporting more architectures".

**Comment by karl0ss** [comment]
.....so....is this currently dead in the water re pypi distribution? as if this isn't going to get fixed "soon" I will need to rethink how I am planning on distrubuting this to my wider audience..

Thanks

**Comment by orhun** [comment]
If I understood correctly, we can move forward with @radusuciu's suggestions above, right?

**Comment by orhun** [comment]
I pushed f675b0b5bdbe57437e39dbe4c0b78e7c4f373936 and planning to create a release soon, let's see

**Comment by orhun** [comment]
Created `v2.2.2` - any chance you can test this again? @karl0ss

**Comment by DeadNews** [comment]
> `v2.2.2`

It works.

**Comment by karl0ss** [comment]
Will have a check today and get back to you, sorry for the delay, and thanks for all the help on this one...

**Comment by karl0ss** [comment]
🥳 Can confirm that 2.2.2 seems to be working for me 😃

**Comment by orhun** [comment]
Awesome! Thanks for your patience and help with this @karl0ss @DeadNews @radusuciu 🚀
