### ISSUE TITLE
The `--current` option involves the release notes of other tags

### ISSUE THREAD

**Issue by kenji-miyake** [orhun/git-cliff#54]
**Describe the bug**

When the commit-graph is like the following, the `--current` option doesn't work correctly.

![image](https://user-images.githubusercontent.com/31987104/151713794-3f8bb081-6bae-4f6b-952c-77a82e749bb4.png)

The `tags` variable was like this.

![image](https://user-images.githubusercontent.com/31987104/151712780-56e4ed81-e4f5-4369-ba5e-979b714cbb3e.png)

However, the current code uses `current_tag_index - 1` for the previous tag.

https://github.com/orhun/git-cliff/blob/848d8a587efd5f611a98b647b954c06938fac24a/git-cliff/src/lib.rs#L169

I think we should find the nearest parent tag here.

**To Reproduce**

I attached my test scripts and the output.
Please save this script and run it.

<details>
<summary>test script</summary>

```bash
#!/bin/bash
set -e

# Set up repository
rm -rf /tmp/test
mkdir -p /tmp/test
cd /tmp/test
git init
git commit --allow-empty -m "Initial commit"

# Create tags
git commit --allow-empty -m "feat: v0.1.0"
git tag v0.1.0
sleep 1

git checkout v0.1.0
git commit --allow-empty -m "feat: v0.2.0"
git tag v0.2.0
sleep 1

git checkout v0.1.0
git commit --allow-empty -m "fix: v0.1.1"
git tag v0.1.1
sleep 1

git checkout v0.2.0
git commit --allow-empty -m "feat: v0.3.0"
git tag v0.3.0
sleep 1

# Show results
git checkout v0.1.0
echo "------"
echo "v0.1.0"
git-cliff --current
echo "------"

git checkout v0.1.1
echo "------"
echo "v0.1.1"
git-cliff --current
echo "------"

git checkout v0.2.0
echo "------"
echo "v0.2.0"
git-cliff --current
echo "------"

git checkout v0.3.0
echo "------"
echo "v0.3.0"
git-cliff --current
echo "------"
```

</details>

Without `sleep`, probably because the commit timestamp will be the same and it won't reproduce the problem.

<details>
<summary>output</summary>

```sh-session
$ ./test.sh
Initialized empty Git repository in /tmp/test/.git/
[main (root-commit) 228dbab] Initial commit
[main 7d5b9fb] feat: v0.1.0
Note: switching to 'v0.1.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 7d5b9fb feat: v0.1.0
[detached HEAD ee77516] feat: v0.2.0
Previous HEAD position was ee77516 feat: v0.2.0
HEAD is now at 7d5b9fb feat: v0.1.0
[detached HEAD 44cfc20] fix: v0.1.1
Previous HEAD position was 44cfc20 fix: v0.1.1
HEAD is now at ee77516 feat: v0.2.0
[detached HEAD 567de7b] feat: v0.3.0
Previous HEAD position was 567de7b feat: v0.3.0
HEAD is now at 7d5b9fb feat: v0.1.0
------
v0.1.0
 WARN  git_cliff > "cliff.toml" is not found, using the default configuration.
# Changelog
All notable changes to this project will be documented in this file.

## [0.1.0] - 2022-01-30

### Features

- V0.1.0

<!-- generated by git-cliff -->
------
Previous HEAD position was 7d5b9fb feat: v0.1.0
HEAD is now at 44cfc20 fix: v0.1.1
------
v0.1.1
 WARN  git_cliff > "cliff.toml" is not found, using the default configuration.
# Changelog
All notable changes to this project will be documented in this file.

## [0.1.1] - 2022-01-30

### Bug Fixes

- V0.1.1

<!-- generated by git-cliff -->
------
Previous HEAD position was 44cfc20 fix: v0.1.1
HEAD is now at ee77516 feat: v0.2.0
------
v0.2.0
 WARN  git_cliff > "cliff.toml" is not found, using the default configuration.
# Changelog
All notable changes to this project will be documented in this file.

## [0.2.0] - 2022-01-30

### Features

- V0.2.0

<!-- generated by git-cliff -->
------
Previous HEAD position was ee77516 feat: v0.2.0
HEAD is now at 567de7b feat: v0.3.0
------
v0.3.0
 WARN  git_cliff > "cliff.toml" is not found, using the default configuration.
# Changelog
All notable changes to this project will be documented in this file.

## [0.3.0] - 2022-01-30

### Features

- V0.3.0

## [0.2.0] - 2022-01-30

### Features

- V0.2.0

<!-- generated by git-cliff -->
------
```

</details>

`0.2.0` is included in `0.3.0`.

```text
## [0.3.0] - 2022-01-30

### Features

- V0.3.0

## [0.2.0] - 2022-01-30

### Features

- V0.2.0
```

**Expected behavior**

The output only includes the tag's changes.

In this case:

```text
## [0.3.0] - 2022-01-30

### Features

- V0.3.0
```

**Comment by kenji-miyake** [comment]
@orhun Could you take a look at this, please? :pray: 

> I think we should find the nearest parent tag here.

If it's okay for you, I can work on it and will send a PR.

**Comment by kenji-miyake** [comment]
@orhun Ah, in this case, should I use `--topo-order`? Then, it seems working correctly.
Are there any reasons for setting this to `false` as the default? (I'll check previous issues.)

**Comment by orhun** [comment]
Hey! Thanks for the detailed report. Yes, `--topo-order` should fix this.

When you run `git cliff --current`, tag list is fetched as follows:

```
v0.1.0
v0.2.0
v0.1.1 -> current_tag_index - 1
v0.3.0 -> current_tag_index
```

Same as running `git log --oneline --all --graph --date-order`:

```
* 8f8d790 feat: v0.3.0 -> current_tag_index
| * 1339a5f fix: v0.1.1 -> current_tag_index - 1
* | bbe64bc feat: v0.2.0
|/  
* e2bb63f feat: v0.1.0
* 000ccf1 Initial commit
```

So current tag is selected between `v0.1.1` and `v0.3.0` since the commits are always topologically sorted.

But if you use `--topo-order`:

```
v0.1.0
v0.1.1
v0.2.0 -> current_tag_index - 1
v0.3.0 -> current_tag_index
```

`git log --oneline --all --graph --topo-order`:

```
* 8f8d790 feat: v0.3.0 -> current_tag_index
* bbe64bc feat: v0.2.0 -> current_tag_index - 1
| * 1339a5f fix: v0.1.1
|/  
* e2bb63f feat: v0.1.0
* 000ccf1 Initial commit
```

Hence the changelog result is correct. 

I probably re-explained the things that you already figured out 😄 

So there are 2 things to investigate at this point:
1. > Are there any reasons for setting this to `false` as the default?
  - since topo-order is already default for `git`, maybe it should be default for `git-cliff`
    - in that case, `--topo-order` flag is unnecessary and should be renamed to `--date-order`
2.  maybe setting `--topo-order` should affect the commit order as well
  - reference: https://github.com/orhun/git-cliff/blob/e1da61150f07f641dfe471e240033e13cc19d089/git-cliff-core/src/repo.rs#L48 

Feel free to look into this and submit a PR. I'm always happy to review/discuss 🐻

**Comment by kenji-miyake** [comment]
@orhun Thank you for the detailed explanation!
> in that case, --topo-order flag is unnecessary and should be renamed to --date-order

Sounds good to me! I'll try to send a PR for this.

**Comment by orhun** [comment]
> > in that case, --topo-order flag is unnecessary and should be renamed to --date-order
> 
> Sounds good to me! I'll try to send a PR for this.

Alright! Please look into how it might affect the current tests and uses cases as well :) Also, configuration file might be changed accordingly.

**Comment by kenji-miyake** [comment]
@orhun Ah, let me confirm one thing. Should I keep the `--topo-order` option to provide a transition phase? Or since this project is still `v0.x`, can I replace it at once?

**Comment by orhun** [comment]
> @orhun Ah, let me confirm one thing. Should I keep the `--topo-order` option to provide a transition phase? Or since this project is still `v0.x`, can I replace it at once?

Yes, I think replacing is safe at this point.
