### ISSUE TITLE
Conflict between "ci" and "chore" commit types

### ISSUE THREAD

**Issue by akarmes** [orhun/git-cliff#540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

I've noticed, that with template like this:
```
commit_parsers = [
  { message = "^ci*", group = "Continuous Integration" },
  { message = "^chore*", group = "Miscellaneous Tasks" },
]
```

Group "Continuous Integration" will capture all `chore` commits. I'm struggling to understand how such simple regex can be interpreted this way. 

It's not a big deal, as I was able to achieve desired result by removing `*`, but it's concerning that it behaves that way and that it can be found only be testing. 

### Steps To Reproduce

- Create 2 commits with messages `ci: ...` and `chore: ...`
- Update `clif.toml` with parsers:
```
commit_parsers = [
  { message = "^ci*", group = "Continuous Integration" },
  { message = "^chore*", group = "Miscellaneous Tasks" },
]
```
- Generate changelog

### Expected behavior

I expect `chore` and `ci` commits to be grouped separately 

### Software information

- Operating system: Manjaro 23.1.3
- Rust version:
- Project version: git-cliff 2.1.2

**Comment by orhun** [comment]
The correct regex is the following (i.e. use `.*` instead of `*`):

```toml
commit_parsers = [
    { message = "^ci.*", group = "Continuous Integration" },
    { message = "^chore.*", group = "Miscellaneous Tasks" },
]
```

`^ci*` matches anything that starts with `c` and that's why both commits are grouped under "Continuous Integration".

You can test the regex here: <https://regex101.com/r/NoaLur/1>
