### ISSUE TITLE
`git-cliff` prints "Function call 'throw' failed" instead of error message passed into Tera `throw()`

### ISSUE THREAD

**Issue by cr1901** [orhun/git-cliff#542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

First of all, thank you for writing `git-cliff`. I find it very useful with the `--unreleased`, `--latest`, `--bump`, and `--current`, `--tag` for aggregating commits for writing prose into my actual `CHANGELOG.md`.

Tera has a [throw](https://keats.github.io/tera/docs/#throw) function for the user to automatically fail rendering the template. I use it to ensure that I remembered to pass some combination of the above flags when rendering the template. Right now, when I invoke `throw` in a minimal config, I get the following error message instead of "the `message` argument to `throw` printed out to the console":

```
Function call 'throw' failed
```

### Steps To Reproduce

1. Create a `cliff.toml` with the following contents:

   ```
   [changelog]
   # template for the changelog body
   # https://keats.github.io/tera/docs/#introduction
   # template for the changelog footer
   footer = """
   {{ throw(message="footer") }}
   """
   ```
3. Run `git cliff` in the same directory as your just-created `cliff.toml`. You will get:

    ```
    $ git cliff
    INFO  git_cliff > A new version of git-cliff is available: v2.0.4 -> v2.1.2
    WARN  git_cliff > Changelog body is not specified, using the default template.
    ERROR git_cliff > Template render error:
   Function call 'throw' failed
   ```

### Expected behavior

I expect the message `footer` (or whatever I passed to `throw`) to be written to the console.

### Software information

- Operating system:
   ```
   william@xubuntu-dtrain:~/Projects/FPGA/amaranth/sentinel$ uname -a
   Linux xubuntu-dtrain 5.4.0-170-generic #188-Ubuntu SMP Wed Jan 10 09:51:01 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
   ```
- Rust version:
   ```
   william@xubuntu-dtrain:~/Projects/FPGA/amaranth/sentinel$ rustc -Vv
   rustc 1.78.0-nightly (98aa3624b 2024-02-08)
   binary: rustc
   commit-hash: 98aa3624be70462d6a25ed5544333e3df62f4c66
   commit-date: 2024-02-08
   host: x86_64-unknown-linux-gnu
   release: 1.78.0-nightly
   LLVM version: 17.0.6
   ```
- Project version:
   ```
   william@xubuntu-dtrain:~/Projects/FPGA/amaranth/sentinel$ git cliff -V
   git-cliff 2.1.2
   ```

### Additional context

According to [Tera's tests](https://github.com/Keats/tera/blob/3b2e96f624bd898cc96e964cd63194d58701ca4a/src/renderer/tests/basic.rs#L723-L738), it seems you have to call `source` twice on the returned error to get the `message` passed into `throw`? I don't know how easy it is to know that `throw` specifically failed and call `source` again within `git cliff`.

```
let err = res.expect_err("This should always fail to render");
let source = err.source().expect("Must have a source");
assert_eq!(source.to_string(), "Function call 'throw' failed");

let source = source.source().expect("Should have a nested error");
assert_eq!(source.to_string(), "Error: hello did not include a summary");
```

**Comment by orhun** [comment]
Hey, this should be resolved via 7ee3c860afac12238d37141566759c17b38ac594

Thanks for reporting and kind words! <3
