### ISSUE TITLE
Messages falsely considered as "conventional"

### ISSUE THREAD

**Issue by thucke** [orhun/git-cliff#548]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

In my repo all commits are following the schema 
* ``JIRA-xxxxx: Lorem ipsum ....."`` or
* ``JIRA-xxxxx Lorem ipsum ....."`` (note the missin colon after xxxxx)

Whereas "JIRA-xxxxx" is the reference to a Jira-Issue ticket.

When I check the context, it comes to the point that entries WITH colon are falsly consideres as "conventional" and those without are classified as un-conventional.

### Steps To Reproduce

- Follow the description to the different commit messages with and without colon.
- check the context how both commits are classified as conventional or un-conventional

### Expected behavior

All commits should be classified un-conventional ("conventional": false)

### Software information

- Operating system: indepentend
- Rust version: (Docker image [sha-ccdc152](https://hub.docker.com/layers/orhunp/git-cliff/sha-ccdc152/images/sha256-eb0bc9b83de625ec40b3eaeab25b58c902b5d4395097f8522b4ecc33aa2dde76?context=explore))
- Project version: 2.1.2

### Additional context

I currently use the latest docker image provided in DockerHub.

**Comment by orhun** [comment]
Hey, have you tried turning off conventional commit parsing?

```toml
[git]
conventional_commits = false
```

I'm not sure if there is anything that we can do because those commits are _conventional_ according to the [`git-conventional`](https://github.com/crate-ci/git-conventional) library - feel free to report it there.

**Comment by thucke** [comment]
Thanks @orhun, I'll think aboout opening an issue for the library.

Anyway .... I saw the chance to use a workaround using a pre-processor.
I'd like to smoothly migrate from the current commit message format to conventional commits.
Therefore I have to keep ``conventional_commits = true``.

A bit weird is that even when I set ``filter_unconventional = false`` all commits that are in the context classified as  ``"conventional": false`` do not appear in the generated CHANGLOG.md

Obviously the library only looks for a colon in the commit to classify it as "conventional".
Then when I configure ``commit_preprocessors = [ { pattern = '(JIRA-\d{1,4})[\ :](.*)', replace = "${1} ${2}" } ]`` I can get rid of that colon.
As a result ALL commits appear with ``conventional_commits = false`` but then no commit appears in the CHANGELOG.md.

Could that be a bug in git-cliff?

**Comment by epage** [comment]
> I'm not sure if there is anything that we can do because those commits are conventional according to the [git-conventional](https://github.com/crate-ci/git-conventional) library - feel free to report it there.

Because they have the appearance of being conventional, there isn't anything git-conventional should do for this.  Obviously you have a flag to disable it or not.  Any further detection logic should exist in the caller as we won't have the context for it.

**Comment by thucke** [comment]
Thank you @epage,

from my point of view it seems that "conventional commits" are not specified dedicated enough.

Messages like ``JIRA-1234: Lorem ipsum`` only appear as conventional if a loose approval is done.
Then ``JIRA-1234`` could be interpreted as a <type> of the conventional commit spec.

In my understanding <type> should be an enumeration of initially defined entries.
Consindering this it could be IMHO assured that only commits that contains a <type> spefified are considered as "conventional".
If the standard allows to define own <type>s it could be feasible to allow a kind of configuration to define an own set of allowed <type> entries.

@orhun:
I could cope with the current situation when using a commit preprocessor that removes the colon after the Jira ticket number.
But then currently all commits that are classified "non-conventional" disappear from the CHANGELOG even when I set ``filter_unconventional = false``.

Therfore I'm currently blocked in this point.
Luckily I can mitigate this turning ALL commits - also those whithout colon - in to a real or unreal conventional one so that they all appear in the generated CHANGELOG.
This is being flanked with a commit rule that only allows "real" conventional commit types and Jira-Ticket references.

Anyway would it be great if ``filter_unconventional = false`` would work as it is dedicated ;-)

Greets
Thomas

**Comment by orhun** [comment]
> Then when I configure ``commit_preprocessors = [ { pattern = '(JIRA-\d{1,4})[\ :](.*)', replace = "${1} ${2}" } ]`` I can get rid of that colon.
As a result ALL commits appear with ``conventional_commits = false`` but then no commit appears in the CHANGELOG.md.
>
> Could that be a bug in git-cliff?

In that case the commits are not being captured by any `commit_parsers` so they couldn't be grouped - that's why they don't appear in the changelog. You can try adding a commit parser such as `{ message = ".*", group = "XYZ" }` and try again.

**Comment by thucke** [comment]
@orhun - that did the trick - thank you very much for your support.
The right combination of pre- and postprocessors and commit-parsing rules could be set up now.
