### ISSUE TITLE
a tera variable or filter for `previous_version`

### ISSUE THREAD

**Issue by sassman** [orhun/git-cliff#55]
For context:
I'm using in my changelog usually links that point to GitHubs version compare pages like this:

```markdown
## [Unreleased]
[Unreleased]: https://github.com/steganogram/stegano-rs/compare/v0.5.0...HEAD

## [0.4.10] - 2021-11-15
[0.4.10]: https://github.com/steganogram/stegano-rs/compare/v0.4.10...v0.4.9
```

so there are links that points to the GitHub code compare, for the actual version (`v0.4.10`) with the "previous" (`v0.4.9`) semver version that was released, and the last released version (`v0.5.0`) with the `HEAD`

In order to make this same changelog available by cliff I've tried the `cliff.toml` as below:

```toml
# template for the changelog body
# https://tera.netlify.app/docs/#introduction
body = """
{% if version %}\
    ## [{{ version | trim_start_matches(pat="v") }}] {{ timestamp | date(format="%Y-%m-%d") }}
    [{{ version | trim_start_matches(pat="v") }}]: https://github.com/sassman/putzen-rs/compare/{{ version }}...{{ previous_version }}
{% else %}\
    ## [unreleased]
    [Unreleased]: https://github.com/sassman/putzen-rs/compare/{{ latest_version }}...HEAD
{% endif %}\
```

I guess this variables could be very tricky to provide, but maybe when assuming semver version tags it might be possible to have them all parsed and prepared for the tera rendering.

Alternatively it might be a filter available that goes to the previous version of a given version number like this:

```toml
    [{{ version | trim_start_matches(pat="v") }}]: https://github.com/sassman/putzen-rs/compare/{{ version }}...{{ version | previous_release }}
```

**Comment by orhun** [comment]
Hey Sven!

Have you tried using the `previous` field which is mentioned in the [template context](https://github.com/orhun/git-cliff#context)?

So you can use it like this to get the same result:

```jinja2
{% if version %}\
    ## [{{ version | trim_start_matches(pat="v") }}] {{ timestamp | date(format="%Y-%m-%d") }}
    [{{ version | trim_start_matches(pat="v") }}]: https://github.com/sassman/putzen-rs/compare/{{ version }}...{{ previous.version }}
{% else %}\
    ## [unreleased]
    [Unreleased]: https://github.com/sassman/putzen-rs/compare/{{ previous.version }}...HEAD
{% endif %}\
```

But be aware, this will only work if you run `git-cliff` with `--unreleased` or `--latest` flags. Otherwise you might get template errors due to `previous.version` not being present. In that case you can add another conditional check to avoid this error.

Hope this helps 🙂
