### ISSUE TITLE
Valid complex regex doesn't match valid commit message

### ISSUE THREAD

**Issue by ArtemkaKun** [orhun/git-cliff#554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

I have a complex regex `^(fix|feat|setup|doc|refactor|test|optimization)\([A-Za-z0-9_-]+\)(, (fix|feat|setup|doc|refactor|test|optimization)\([A-Za-z0-9_-]+?\))+(:\ .*)$` that matches commit message `doc(repo), setup(ci): improve PR naming section in CONTRIBUTING`

![image](https://github.com/orhun/git-cliff/assets/36485221/63040298-7f24-4e66-9d5b-83570fe61652)

But for some reason, commit parser `{ message = '^(fix|feat|setup|doc|refactor|test|optimization)\([A-Za-z0-9_-]+\)(, (fix|feat|setup|doc|refactor|test|optimization)\([A-Za-z0-9_-]+?\))+(:\ .*)$', group = "TEST", default_scope = "other"}` doesn't match this commit message when using this regex.

### Steps To Reproduce

# Config

```
[changelog]
body = """
{% if version %}\
    # [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}\
{% else %}\
    # [unreleased]\
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}\
    \n
    ## {{ group | upper_first }}\
    {% for group, commits in commits | group_by(attribute="scope") %}\
    	\n
        ### {{ group | upper_first }}\n\
        {% for commit in commits | unique(attribute="message") %}\
            \n- {{ commit.message | split(pat="\n") | first | trim }}\
              {% if commit.github.username %} by @{{ commit.github.username }}{% endif %}\
              {% if commit.github.pr_number %} in #{{ commit.github.pr_number }}{% endif %}\
    	{% endfor %}\
    {% endfor %}\
{% endfor %}\
\n
## First-time contributors 🥳\n\
{% for contributor in github.contributors | filter(attribute="is_first_time", value=true) %}\
    \n- @{{ contributor.username }} made their first contribution in #{{ contributor.pr_number }}\
{% endfor %}\
"""

trim = true

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false

commit_parsers = [
    { message = '^(fix|feat|setup|doc|refactor|test|optimization)\([A-Za-z0-9_-]+\)(, (fix|feat|setup|doc|refactor|test|optimization)\([A-Za-z0-9_-]+?\))+(:\ .*)$', group = "TEST", default_scope = "other"},
    { message = "^feat", group = "✨ Features" },
    { message = "^fix", group = "🪲 Bug Fixes" },
    { message = "^doc", group = "📚 Documentation" },
    { message = "^optimization", group = "🚀 Performance" },
    { message = "^refactor", group = "🧹 Refactor" },
    { message = "^setup", group = "⚙️ Configuration" },
    { message = "^test", group = "✅ Testing" }, 
]

protect_breaking_commits = false
filter_commits = false
tag_pattern = "v[0-9].*"
skip_tags = ""
ignore_tags = ""
topo_order = false
sort_commits = "oldest"
```

### Expected behavior

The commit message `doc(repo), setup(ci): improve PR naming section in CONTRIBUTING` is visible in `TEST` section in the `Other` group

### Software information

- Operating system: Linux
- Rust version: idk, I'm using Arch linux package https://archlinux.org/packages/extra/x86_64/git-cliff/
- Project version: git-cliff 2.1.2

**Comment by ArtemkaKun** [comment]
If I remove `$` end match symbol from regex - it matches the commit message as expected 🤔 Is it related to the additional `\n` or spaces at the end of the commit message?

**Comment by ArtemkaKun** [comment]
Hi, thanks for the response. It's actually the tough one.

I think the process should start from research why there is `\n` at the end of common commit message without body and without `\n` at the end. Maybe this is how GitHub sends it. If so, probably the tool should trim this kind of new line character.

If this is something that Git do for some reasons and the tool can't automatically remove new line character because of reasons or edgecases or complex implementation - it should definitely appear in the documentation so users be aware of it.

**Comment by orhun** [comment]
I decided to always trim it: #573

The commit message originally has a newline at the end because of `git2` and I already trimmed that in #403 

So doing this won't hurt I reckon :)
