### ISSUE TITLE
Bitbucket Integration

### ISSUE THREAD

**Issue by mdawart** [orhun/git-cliff#566]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

Integrate with Bitbucket

### Desired solution

Be able to use generated links in footer for Bitbucket cloud

### Alternatives considered

Changing the changelog footer configuration

**Comment by orhun** [comment]
Not a priority but I might get to this in the future 🐻 I'm not using Bitbucket and I'm also not familiar with their API

**Comment by dark0dave** [comment]
I'll take this one

**Comment by dark0dave** [comment]
@mdawart this is now done. Let us know if it works for you!

**Comment by mdawart** [comment]
Thank you for that 🙏 I assume I need to wait for this to be added to a new release, correct?

**Comment by orhun** [comment]
yup, will be out very soon!

**Comment by orhun** [comment]
it's now live! 🥳 

- https://git-cliff.org/docs/integration/bitbucket

**Comment by mdawart** [comment]
Great, I was quickly checking the Bitbucket API-Connection and will test this more detailed during our next release. 

Is there also the chance to link the (Jira)-Tickets we add via e.g. Relates: XY-123 like you have it on https://github.com/orhun/git-cliff/releases for the linked issues?

**Comment by orhun** [comment]
Yes, you can probably do something like that via parsing the commit messages/descriptions. I can say something more certain if you can share your use-case in another issue along with some example commits :)
