### ISSUE TITLE
Detecting default config file should include Cargo.toml

### ISSUE THREAD

**Issue by alerque** [orhun/git-cliff#568]
I'm trying to setup `git cliff` (2.1.2) in a Rust project repository workspace that has several crates. I prefer not to clutter up the repo with tooling configs, so adding a section to the crate meta data seemed perfect. I added:

```toml
[workspace.metadata.git-cliff.changelog]
...
```

But running `git cliff` said it couldn't find a config:

```
 WARN  git_cliff > "cliff.toml" is not found, using the default configuration.
```

I would have expected it to look both in the default location and in known project meta data locations for setup info before giving up and reverting to defaults.

**Comment by orhun** [comment]
Hey, this should be fixed in #571 

Can you check out locally and test this out plz? It's 4:20am and my brain is not braining anymore.
