### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by prewk** [orhun/git-cliff#582]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

https://git-cliff.org/ = 404

### Steps To Reproduce

Go to https://git-cliff.org/

### Expected behavior

not 404

### Screenshots / Logs

<img width="653" alt="image" src="https://github.com/orhun/git-cliff/assets/640102/e778866f-f874-42ff-9233-34904f79197b">

### Software information

Cutting edge Chromium web browser technology

**Comment by alerque** [comment]
Gonna guess 82839549a541812d1410fdf8fe16b15237984a71 and https://mastodon.social/@orhun@fosstodon.org/112170002951201214 are related to this.

**Comment by orhun** [comment]
Yeah, I was trying to set up preview deployments and then some stuff happened. Should be back up now.
