### ISSUE TITLE
CHANGELOG.md with pre-release versions

### ISSUE THREAD

**Issue by lictw** [orhun/git-cliff#588]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

I have pre-release `rc.*` tags and would like to generate CHANGELOG.md with them. Now, without any options pre-release tags considered like everything else, so I will have notes for `rc.*`, but when I release new version git-cliff will generate notes only from latest RC tag, not from latest stable tag.

For clarify, for tags 2.0, 2.1-rc.0, 2.1-rc.1, and 2.1 I want:
2.0 -> 2.1-rc.0
2.1-rc.0 -> 2.1-rc.1
2.0 -> 2.1

<sub>Also I don't understand use-cases of `skip_tags` option, can you explain? For ex. if it `alpha`, does it drop all commits from any matched prev. tag to obtained alpha tag, for what can I need this?)</sub>

### Desired solution

Separated logic for stable and pre-release tags.

### Alternatives considered

Only manual approach with combinations of `tag-pattern` (include/exclude pre-release tags) (or `ignore_tags`, but it's 2 mostly repeatable configs, no CLI option) and `--prepend` option one by one from version to version, I can't find any way to generate all file with my requirements.

**Comment by orhun** [comment]
Hello!

> Also I don't understand use-cases of skip_tags option, can you explain? For ex. if it alpha, does it drop all commits from any matched prev. tag to obtained alpha tag, for what can I need this?)

For example:
```toml
# regex for skipping tags
skip_tags = "beta|alpha"

# regex for ignoring tags
ignore_tags = "rc"
```

Consider this release history:

`v0` -> `v1-alpha` -> `v1-beta` -> `v1-rc.0` -> `v1`

- Commits for `beta` and `alpha` releases won't appear in the changelog.
- Commits for `rc` will appear under the most recent tag (`v1`)

So `ignore_tags` will move all of the commits contributing to those tags into the next non-ignored tags. Thus it also affects commits that themselves are not tagged.

Whereas `skip_tags` completely drops the tagged commits from processing but doesn't affect any other commits.

Let me know if this works for your use case and if there is anything else that I can help you with! 🐻
