### ISSUE TITLE
npm v2.2.0 is missing index.js for esm and cjs folders

### ISSUE THREAD

**Issue by aminya** [orhun/git-cliff#591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

The v2.2.0 version released last week is missing the `index.js` for the lib/esm and lib/cjs folders. This results in the programmatic API not working when importing.

https://www.npmjs.com/package/git-cliff?activeTab=code

### Steps To Reproduce

```ts
import { runGitCliff } from 'git-cliff';
```

### Expected behavior

The files should be included in the release

### Software information

- Operating system: N/A
- Rust version: N/A
- Project version: 2.2.0

**Comment by favna** [comment]
I was alerted of this as well just now in my own support server for cliff-jumper. This is my fault from an earlier PR and I will be working on getting a new PR out ASAP (starting work right now)

**Comment by orhun** [comment]
Will create a patch release soon.
