### ISSUE TITLE
Does not work with conventional Pull Request commit messages without body 

### ISSUE THREAD

**Issue by mjhipp** [orhun/git-cliff#6]
**Describe the bug**
Fails to parse conventional commit messages made from squashing and merging Pull Requests if there is no body message.

**To Reproduce**
1. Squash and merge a pull request (using conventional commits), without adding a body message
2. Try to create a changelog using extra verbose option
3. See the `TRACE` messages and the missing commits from the changelog

**Expected behavior**
These PR commit messages can be parsed as normal
 
**Screenshots/Logs**
I did these steps on a fork of this repo: https://github.com/mjhipp/git-cliff

Created pull requests, and merged them:

![Screen Shot 2021-09-02 at 4 52 55 PM](https://user-images.githubusercontent.com/19941609/131931190-0b7fe1de-ede0-4750-b0e0-23884cd8423e.png)

one of them I added an extra message:

![Screen Shot 2021-09-02 at 4 49 25 PM](https://user-images.githubusercontent.com/19941609/131931184-3251cf47-246a-4f74-a513-e807293a9079.png)

The git log:

![Screen Shot 2021-09-02 at 4 55 01 PM](https://user-images.githubusercontent.com/19941609/131931303-8d7df460-a73a-4148-994b-fbf055b94e35.png)

Then tried to create a changelog:

![Screen Shot 2021-09-02 at 5 09 07 PM](https://user-images.githubusercontent.com/19941609/131931310-aed7c708-d0bc-4852-ac1f-bc4bf21f8bfe.png)

It is not the parenthesis or `#`, because it works if I commit directly:

![Screen Shot 2021-09-02 at 5 12 11 PM](https://user-images.githubusercontent.com/19941609/131931509-bfac6266-adb7-482c-b05b-22d1ee89c295.png)

![Screen Shot 2021-09-02 at 5 12 22 PM](https://user-images.githubusercontent.com/19941609/131931516-7cfa048d-d0f8-4fc9-96b5-29d023799bd3.png)

If I perform an interactive rebase and "reword" the commits, without actually changing anything, the commits can then be parsed:

![Screen Shot 2021-09-02 at 5 15 31 PM](https://user-images.githubusercontent.com/19941609/131931749-27196c43-5a45-485b-940e-1a84aaa2169e.png)
![Screen Shot 2021-09-02 at 5 16 28 PM](https://user-images.githubusercontent.com/19941609/131931754-9d684496-1b64-4a59-b7cf-670a63188185.png)

**System (please complete the following information):**
 - OS Information: MacOS and `ubuntu-latest` for `git-cliff-action`
 - Project Version: `0.1.0` and `git-cliff-action@v1`

**Additional context**
Sorry for the long post! This is a great tool and I would really like to be able to use it with squashed PRs!

**Comment by mjhipp** [comment]
This has already been fixed upstream!

https://github.com/crate-ci/git-conventional/issues/12#issuecomment-912587335

https://github.com/orhun/git-cliff/blob/ae8821aaa537f597762206647c18e9ac69289b6a/Cargo.lock#L377-L381

**Comment by orhun** [comment]
Thanks for investigating/reporting this! I'll release a new version to fix this soon.
