### ISSUE TITLE
Comply with MD022?

### ISSUE THREAD

**Issue by kenji-miyake** [orhun/git-cliff#60]
**Is your feature request related to a problem? Please describe.**

The default configuration generates the changelog that violates a `markdownlint` rule [MD022](https://github.com/DavidAnson/markdownlint/blob/v0.25.1/doc/Rules.md#md022).

![image](https://user-images.githubusercontent.com/31987104/152683205-8b1d6354-8d41-4218-a286-513f50a37ac4.png)

If there are no reasons for this, I feel it would be nice to comply with `MD022`.

**Describe the solution you'd like**

Just to add `\n` after `# Changelog`.

Before:

```toml
header = """
# Changelog
All notable changes to this project will be documented in this file.\n
"""
```

After:

```toml
header = """
# Changelog\n
All notable changes to this project will be documented in this file.\n
"""
```

**Describe alternatives you've considered**

Replace `\n` with a newline.

```toml
header = """
# Changelog

All notable changes to this project will be documented in this file.\n
"""
```

**Additional context**

Nothing.

**Comment by kenji-miyake** [comment]
@orhun How do you feel about it? If you don't mind, I'll send a PR.

**Comment by kenji-miyake** [comment]
Also, let me confirm one more small thing here.

The word `whitespaces` will cause a spell-check error, so can I replace it with `whitespace` or `whitespace characters`?
https://github.com/orhun/git-cliff/blob/e1da61150f07f641dfe471e240033e13cc19d089/config/cliff.toml#L24

Reference: https://english.stackexchange.com/questions/25368/what-is-the-plural-form-of-whitespace

**Comment by orhun** [comment]
> @orhun How do you feel about it? If you don't mind, I'll send a PR.

> Also, let me confirm one more small thing here.
> 
> The word `whitespaces` will cause a spell-check error, so can I replace it with `whitespace` or `whitespace characters`?
> 
> https://github.com/orhun/git-cliff/blob/e1da61150f07f641dfe471e240033e13cc19d089/config/cliff.toml#L24
> 
> Reference: [english.stackexchange.com/questions/25368/what-is-the-plural-form-of-whitespace](https://english.stackexchange.com/questions/25368/what-is-the-plural-form-of-whitespace)


Both things sound totally reasonable 👍🏼  Please go ahead and submit a PR.

**Comment by kenji-miyake** [comment]
@orhun Thank you, submitted #61.

By the way, there are some other rules that we can follow. How about these?
https://github.com/DavidAnson/markdownlint/blob/v0.25.1/doc/Rules.md#md004
https://github.com/DavidAnson/markdownlint/blob/v0.25.1/doc/Rules.md#md040

It is useful to use [markdownlint-cli](https://github.com/igorshubovych/markdownlint-cli), [Prettier](https://prettier.io/), and [pre-commit.ci](https://pre-commit.ci/)

If you are interested, I can introduce them to this repository.

The sample settings are:
https://github.com/autowarefoundation/autoware/blob/27ba4d26c2597242f018da8f89b7126bba32825d/.markdownlint.yaml
https://github.com/autowarefoundation/autoware/blob/27ba4d26c2597242f018da8f89b7126bba32825d/.prettierrc.yaml
https://github.com/autowarefoundation/autoware/blob/27ba4d26c2597242f018da8f89b7126bba32825d/.pre-commit-config.yaml#L22-L31
