### ISSUE TITLE
Filter commits without body

### ISSUE THREAD

**Issue by bbbenja** [orhun/git-cliff#604]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

I want to use the `commit_parsers` to skip commits without body messages.

### Desired solution

`{ body = null, skip= true }`

### Alternatives considered

I try to use `commit_preprocessors` to add a breakline on all commits and generate a body but those breaklines are then shown in changelog file.

**Comment by orhun** [comment]
Hey!

I created #605 for fixing this! Can you possibly check and test it out maybe?

I'm pretty confident that it's in a good shape though.

Thanks for creating this issue 🐻
