### ISSUE TITLE
Regex preprocess commit messages

### ISSUE THREAD

**Issue by hypervtechnics** [orhun/git-cliff#62]
**Is your feature request related to a problem? Please describe.**
Our CI system prepends all changes which are merged by using the PR functionality (by policy everyone has to do so) with "Merged PR xxx: <original message>". This does not comply with the conventional commit message format.

**Describe the solution you'd like**
Something like a commit message preprocessor which enables us to remove or select certain parts of the commit message/body to be used in the following processes.

**Describe alternatives you've considered**
Removing that prefix, which is unfortunately not possible.

**Comment by hypervtechnics** [comment]
This is totally great! Thank you for it 😄

**Comment by vovkanaz** [comment]
How to ingest the result of this preprocessed message into the template? Or we should use post_processor?
