### ISSUE TITLE
Allow including tag-message in changelog

### ISSUE THREAD

**Issue by chrichrichri** [orhun/git-cliff#623]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

To have a "headline" for a release, it would be great allow including tag-messages (of release tags) into the changelog. For example, a changelog including this headline could look like this:

```
# Changelog

All notable changes to this project will be documented in this file.

## [1.0.1] - 2021-07-18

This is the release-tag message

### Miscellaneous Tasks
- Add release script

### Refactor

- Expose string functions
```

### Desired solution

Provide variable (such as `tag_message`) to the context, so it can be used as a variable within the changelog template.

### Alternatives considered

N/A

**Comment by orhun** [comment]
Pretty good idea! The implementation should be pretty straightforward thanks to [`Tag::message`](https://docs.rs/git2/latest/git2/struct.Tag.html#method.message) method. Marked as good first issue.

**Comment by alerque** [comment]
This will get into cart vs. horse territory for many projects as the finished changelog is expected inside the tagged commit not later. Perhaps an env var could be used to hold the tag message and then used both for the changelog and subsequent actual tag message.

**Comment by orhun** [comment]
Or maybe we can add a new argument similar to [`--with-commit`](https://git-cliff.org/docs/usage/adding-commits) such as `--tag-message`?
