### ISSUE TITLE
"version" key (which is the tag) is coming as null when using git-cliff npm. But the same works using terminal

### ISSUE THREAD

**Issue by suhas-cashfree** [orhun/git-cliff#651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

"version" key (which is the tag) is coming as null when using git-cliff npm. But the same works using terminal

### Steps To Reproduce

npm i git-cliff
add a repository to read commits from with --context, --output, --context.json
see the context.json file

### Expected behavior

context.json file has version value as null
It should have a tag value

### Software information

- Operating system: macOS
- Rust version:
- Project version: 2.2.2

**Comment by orhun** [comment]
There might be confusion here. The top level `version` value refers to the current version, `null` means that there might be unreleased changes. Can you check again?

I get the same result for both `git-cliff --context` and `npx git-cliff --context`:

```shell
$ git clone https://github.com/orhun/git-cliff && cd git-cliff

$ git-cliff --no-exec --context | jq .[].version | head -n 5
null
"v2.2.2"
"v2.2.1"
"v2.2.0"
"v2.1.2"

$ npx git-cliff --no-exec --context | jq .[].version | head -n 5
null
"v2.2.2"
"v2.2.1"
"v2.2.0"
"v2.1.2"
```

**Comment by suhas-cashfree** [comment]
Understood. Thank you @orhun
