### ISSUE TITLE
Add installation instructions for Nix

### ISSUE THREAD

**Issue by orhun** [orhun/git-cliff#668]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

It would be nice to add instructions for Nix, similar to other installation docs, e.g. <https://git-cliff.org/docs/installation/arch-linux>

### Desired solution

Add `Nix.md` under `website/docs/installation`

### Alternatives considered

None.

### Additional context

See <https://search.nixos.org/packages?channel=24.05&show=git-cliff&from=0&size=50&sort=relevance&type=packages&query=git-cliff>

**Comment by 0x61nas** [comment]
Hi, I would love to work on this, please assign this issue to me if there's no one are already working on it

**Comment by orhun** [comment]
sir, you got it
