### ISSUE TITLE
Make repository name available in context

### ISSUE THREAD

**Issue by The-Engineer** [orhun/git-cliff#685]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

I am creating a consolidated changelog for multiple repositories building a monolith using the `--repository` flag with three repos. The changelog gets generated but theres no reference which changelog refers to which repo, just the repos most current tags.
In the current context there's just details about commits but not about the repo name or url.

### Desired solution

It would be nice to have the repo name (and url?) available in the context to have something like this:

`config:` [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }} -- {{ repo.name }}

which would look like this: 

## [1.2.3] - 2024-06-07 - orhun/git-cliff

changes ...

## [4.5.6] - 2024-06-07 - another/repo

changes...

### Alternatives considered

The closes thing I currently see to achieve this are commit parsers which allow me to run commands on the OS. But I am not sure how to use that in the body heading to call git and get the repo name. I tried putting a placeholder in the body
`## [unreleased] - REPO_URL` and then tried a postprocessor:

postprocessors = [
  { pattern = 'REPO_URL', replace_command = "basename -s .git `git config --get remote.origin.url`" },
]

this leads to the entire changelog dissappering and setting the reponame where the CI runs three times and not the individual ones :(

**Comment by orhun** [comment]
Hello!

You can do something like this:

```sh
git cliff --github-repo orhun/git-cliff
```

Then in the template:

```
{{ remote.github.owner }}/{{ remote.github.repo }}
```

See the following links for more information:

- https://git-cliff.org/docs/configuration/remote
- https://git-cliff.org/docs/integration/github

**Comment by The-Engineer** [comment]
that sounds good but i am using a selfhosted Gitlab. Do i have to compile cliff to be able to use it? and does it work for multiple repos or just one?

**Comment by orhun** [comment]
Similarly, you can do the same for GitLab:

```sh
GITLAB_API_URL="<your self hosted url>" git cliff --gitlab-repo orhun/git-cliff
```

Then in the template:

```
{{ remote.gitlab.owner }}/{{ remote.gitlab.repo }}
```

See the following links for more information:

- https://git-cliff.org/docs/configuration/remote
- https://git-cliff.org/docs/integration/gitlab

**Comment by The-Engineer** [comment]
Thanks a lot for the idea and docs links but this is still not working.

When I use three repos, the one with changes and the CI and two other ones with their changes.
If I run git cliff with API URL, token and --gitlab-repo path1/repo1 --repository= ./ path2/repo2 path3/repo3

In the result changelog all repos have the reponame repo1 when using `{{ remote.gitlab.repo }}`

**Comment by orhun** [comment]
Oh, it's expected that it might not work with multiple repos. I didn't try it out like that before and it's fetching the commits for only one repo...

**Comment by The-Engineer** [comment]
ohh, ok, thanks a lot for checking! But could you make it possible to read the repos in the base implementation as part of the --repository flag and independent of the gitlab/github/... integrations?
In the individual repo folders you got all the info present about the repos and its not so useful to aggregate changes and not not knowing where they come from :(

this is an awesome project and this addition would make it a very valuable tool

**Comment by orhun** [comment]
> ohh, ok, thanks a lot for checking! But could you make it possible to read the repos in the base implementation as part of the --repository flag and independent of the gitlab/github/... integrations?

Do you mean making e.g. the directory name available in context?

**Comment by The-Engineer** [comment]
Yes the directory name would work

**Comment by orhun** [comment]
Okay, I just checked and I'm not sure where in context we can add the repository path.

The context is currently an array of releases, updating that structure will be a breaking change.

**Comment by The-Engineer** [comment]
Thank you very much for your effort, I have no experience in Rust yet and can't make a code suggestion myself :(
Can't you append the repo name at the same position where you keep the repos tag version number? Or is that not a kind of list/array?

**Comment by orhun** [comment]
You can take a look at https://git-cliff.org/docs/templating/context for getting an idea.

To oversimplify it:

```json
[
  {
    "version": "v0.1.0-rc.21"
  },
  {
    "version": "v0.1.0-rc.20"
  }
]
```

We can add the repo path to each item here, but it would be really redundant :/

**Comment by The-Engineer** [comment]
If theres just a changelog created for the current repo its not really needed, I agree. But when using the --repository flag and multiple repos it should be a good addition in my opinion.

I also tried it with a postporcessor and some git commands and a replace of a placeholder, but that made the whole changelog disappear and just header and footer were left. I am at a different computer this week and can't access the snippet currently

**Comment by orhun** [comment]
Second thought: this actually sounds useful!

Implemented in #721 - any chance that you could test it? 😊

**Comment by The-Engineer** [comment]
awesome thank you so much. I will be able to test it it on sunday or monday and will let you know!

**Comment by The-Engineer** [comment]
I tried to build the branch in a container based on `rust:alpine` following your [docs](https://git-cliff.org/docs/installation/build-from-source) with the command

```bash
apk add git zlib libgit2 && \
git clone -b feat/add_repository_to_context https://github.com/orhun/git-cliff && \
cd git-cliff/ && \
CARGO_TARGET_DIR=target cargo build --release
```

But it fails with ther error
```
error occurred: Command "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "include" "-I" "/git-cliff/target/release/build/ring-b443f8a0fdd469dc/out" "-Wall" "-Wextra" "-fvisibility=hidden" "-std=c1x" "-Wall" "-Wbad-function-cast" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wnested-externs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wstrict-prototypes" "-Wundef" "-Wuninitialized" "-g3" "-DNDEBUG" "-o" "/git-cliff/target/release/build/ring-b443f8a0fdd469dc/out/a9af75d892b04b75-p256-nistz.o" "-c" "crypto/fipsmodule/ec/p256-nistz.c" with args cc did not execute successfully (status code exit status: 1).
```

Is there something missing in the branch or docs?

**Comment by The-Engineer** [comment]
I build myself a modified Docker image derived from your multistage build. The chaneglog looks way better now 
```markdown
All notable changes to this project will be documented in this file.

## [4.5.6] - 2024-06-23 - git-cloned-dep-repos/git-cliff-sub-b

### 🚀 Features

- Big feature in repo B

## [1.2.3] - 2024-06-23 - git-cloned-dep-repos/git-cliff-sub-a

### 🚀 Features

- Some change in repo A

## [0.0.6] - 2024-06-23 - ./

### 🚀 Features

- Add basename cmd

```

I am currently processing the current repo and two more which i clone into the CI and then run `git cliff --output CHANGELOG.md --repository ./ git-cloned-dep-repos/git-cliff-sub-a git-cloned-dep-repos/git-cliff-sub-b` . The base repos name is just mentioned as `./` which is not so helpful. 
Could it be possible to get the repo name via the command 
```bash
basename -s .git `git config --get remote.origin.url`
```
into the context?

**Comment by orhun** [comment]
Thanks for testing!

> Could it be possible to get the repo name via the command

That would mean that we will be executing OS commands which might change across different platforms + we will be depending on `basename` & `git` commands. I'm not very positive with that :)

What's wrong with using the raw paths that are provided via args again?

**Comment by The-Engineer** [comment]
Thats a good point, i get you. With the current implementation I get a little too much in the path. In case of the cloned external repos I also get the temporary folder I created in the CI and in case of the current repo the CI its running in I dont get the repo name :(

For the first part it would help to leave out all path folders except the last. For the second looking into the repo git config is a good solution. I think assuming that git is present should be ok when using your tool?

**Comment by orhun** [comment]
> For the first part it would help to leave out all path folders except the last. 

Can you elaborate this? I didn't get it fully.

> For the second looking into the repo git config is a good solution. I think assuming that git is present should be ok when using your tool?

Sorry I don't want to shell out and call `git`, but if there is a way to do it with [`git2`](https://docs.rs/git2) or any other Rust crate then I might be up for it.

**Comment by The-Engineer** [comment]
Sure no problem. In my CI I created a folder git-cloned-dep-repos and cloned the remote repos into it to process them via the --repository flag. This lead to the result that the `{{ repository }}` placeholder then filled in the repo name as `git-cloned-dep-repos/git-cliff-sub-a` and `git-cloned-dep-repos/git-cliff-sub-b`. It used the full path from the workspace root and not just the repo name which is the last folder in the path.

To the second part regarding calling git, could it be a solution to parse the git config (`.git/config`) which should always be present as plain text? Then you don't need other binarys and just test file parsing :)

**Comment by orhun** [comment]
> It used the full path from the workspace root and not just the repo name which is the last folder in the path.

This might be a preference based on different use cases - someone else might want it to see the full path so I will leave that up to the user to process it via template functions :)

>  which should always be present as plain text? Then you don't need other binarys and just test file parsing :)

If the purpose is just to get the value of `git config --get remote.origin.url` then it is already available as `{{ remote.gitlab.repo }}
`. The only issue that needs fixing is that it won't work with multiple repos yet.. which I might fix in the future.

The requirements are not super clear and I'm not fully convinced that we need to parse `.git/config` yet :)

Btw I will merge #721 - it should be good to go as is 🐻

**Comment by The-Engineer** [comment]
Fair point, thank you for your work and taking the time for this lengthly discussion with me. This is a very cool project of yours 🤙
