### ISSUE TITLE
Broken search in docs https://git-cliff.org/docs/

### ISSUE THREAD

**Issue by bukowa** [orhun/git-cliff#693]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

Searching on https://git-cliff.org/docs/ is broken.

### Steps To Reproduce

1. Go to https://git-cliff.org/docs/
2. Search in top right corner.
3. All results 404

### Additional context

Looks like it's duplicating:
`https://git-cliff.org/docs/templating/context/docs/templating/context#breaking-changes`
instead of 
`https://git-cliff.org/docs/templating/context/#breaking-changes`

**Comment by orhun** [comment]
fixed in 8a9f9f48da42ec95f47a169370c6c5cdf2a0b327, thanks for reporting!
