### ISSUE TITLE
Make changelog.header into a template

### ISSUE THREAD

**Issue by Cyclonit** [orhun/git-cliff#697]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

Currently only `changelog.body` and `changelog.footer` are processed as Tera templates. Making `changelog.header` a template improves parity between the three parts of the changelog.

### Desired solution

- The processing of `changelog.header` will be aligned with that of `changelog.body` and `changelog.footer`.
- The template in `changelog.header` gets the same context as that in `changelog.footer`.

### Alternatives considered

none

**Comment by orhun** [comment]
+1 to this, will check the PR soon.

**Comment by Cyclonit** [comment]
The feature was implemented in #698.
