### ISSUE TITLE
Fixture test script not working on Windows (MINGW64)

### ISSUE THREAD

**Issue by bukowa** [orhun/git-cliff#705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

`test-fixtures-locally.sh` is not working on `Windows` when executed in `bash` provided by `git` installation (`C:\Program Files\Git\bin\bash.exe`

```sh
$ .github/fixtures/test-fixtures-locally.sh test-date-order
error: manifest path `/c/Users/buk/WebstormProjects/git-cliff/.github/fixtures/../../Cargo.toml` does not exist
```

Solution that works for me:
```sh
SCRIPT_DIR=$(cygpath -w "$SCRIPT_DIR")
FIXTURES_DIR=$(cygpath -w "$FIXTURES_DIR")
```

### Steps To Reproduce

```sh
$ .github/fixtures/test-fixtures-locally.sh test-date-order
error: manifest path `/c/Users/buk/WebstormProjects/git-cliff/.github/fixtures/../../Cargo.toml` does not exist
```

### Expected behavior

It works.

### Software information

- Operating system: Windows
- Rust version:
- Project version:

### Additional context

_Originally posted by @orhun in https://github.com/orhun/git-cliff/pull/696#discussion_r1641243322_

**Comment by orhun** [comment]
It would be nice to detect if this is being run on Windows and set those environment variables.

Unfortunately I don't have a Windows machine to test this.

**Comment by bukowa** [comment]
> It would be nice to detect if this is being run on Windows and set those environment variables.

What do you think? Works for me.
```sh
# Check if we are running on Windows with MINGW64 and if cygpath is available
if [ -n "$MSYSTEM" ] && [ "$MSYSTEM" = "MINGW64" ]; then
  echo "Running inside MINGW64 trying to convert paths to Windows format."
  if command -v cygpath > /dev/null 2>&1; then
    # Convert the path to Windows format
    SCRIPT_DIR=$(cygpath -w "$SCRIPT_DIR")
    FIXTURES_DIR=$(cygpath -w "$FIXTURES_DIR")
  else
    echo "WARNING: cygpath command not found in the PATH. The script may not work correctly on Windows."
    exit 1
  fi
fi
```

**Comment by orhun** [comment]
LGTM, feel free to send a PR!
