### ISSUE TITLE
Add `GIT_CLIFF_` prefix to environment variables

### ISSUE THREAD

**Issue by uyha** [orhun/git-cliff#74]
**Is your feature request related to a problem? Please describe.**
Currently, `git-cliff` uses many environment variables without prefixing it with `GIT_CLIFF_`, which causes surprises when I have set up environment variables like `CONFIG` in my startup script and then `git-cliff` behaves weirdly.

**Describe the solution you'd like**
Prefixing all environment variables with `GIT_CLIFF_`

**Describe alternatives you've considered**
Prefixing all environment variable with `CLIFF_`

**Comment by kaushalmodi** [comment]
Thanks. This issue was causing problem in https://github.com/orhun/git-cliff/issues/75 because I had `INCLUDE_PATH` set for GCC which was clashing with git cliff's `INCLUDE_PATH`.
