### ISSUE TITLE
Add Nix Dev environment for easier reproducible dev envs 

### ISSUE THREAD

**Issue by tonybutt** [orhun/git-cliff#743]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

I would like to just type `nix develop` to begin contributing and get parity with CI and other devs. By defining the dependencies of this project in a flake you could ensure everyone on any OS is building as the project expects.

Will submit a draft PR for testing.

### Desired solution

Use Nix

### Alternatives considered

None

**Comment by orhun** [comment]
Unfortunately I don't have experience with Nix but I'm totally fine with it if anyone wants to add it.
