### ISSUE TITLE
$ anchor in commit_preprocessors not works

### ISSUE THREAD

**Issue by uqix** [orhun/git-cliff#745]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

`$` anchor in `commit_preprocessors` not works

### Steps To Reproduce

1. `commit_preprocessors`: `[{ pattern = ' #\d+$', replace = ""}]`
2. Commit: `fix: bug 3. #123`

### Expected behavior

* Expected: `- Bug 3.`
* Got `- Bug 3. #123`

### Software information

- Operating system: macOS 14.5
- Rust version: 1.79.0
- Project version: 2.4.0

**Comment by orhun** [comment]
Hey, thanks for reporting!

Should be fixed in #872 

See #554 for some context (TL;DR: you can use `'#\d+\n'`)
