### ISSUE TITLE
merge identical commit messages

### ISSUE THREAD

**Issue by RickSKy** [orhun/git-cliff#755]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

Sometimes multiple code submissions may be made to solve the same problem, resulting in the same content in the commit message. This can lead to duplicate entries in the automatically generated descriptions of git-cliff. Is it possible to merge identical commit messages?

### Desired solution

merge identical commit messages

### Alternatives considered

none

### Additional context

none

**Comment by orhun** [comment]
You can use the `unique` filter of Tera as follows:

```
{% for commit in commits | unique(attribute="message") %}
```
