### ISSUE TITLE
Config environment variables are not respected when cliff.toml is not found

### ISSUE THREAD

**Issue by marsom** [orhun/git-cliff#777]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

Environment variable GIT_CLIFF__BUMP__INITIAL_TAG  is not respected by `git-cliff  --bumped-version`

I have projects with are versionn with a v-Prefix i.e. v0.2.0 and some with 0.2.0. most projects are with v-Perfix, i tried to set the initial to to e.g. v0.2.0 hand hopped that the intial tag would be v0.2.0.

### Steps To Reproduce

```shell
mkdir upstream
cd upstream
git init
git switch --create main
echo a > text.txt
git add text.txt
git commit -m "fix: test"
cd ..
git clone upstream cloned
cd cloned
```

OK: i expect 0.1.0
```shell
git-cliff --bumped-version
 WARN  git_cliff > "cliff.toml" is not found, using the default configuration.
 WARN  git_cliff_core::release > No releases found, using 0.1.0 as the next version.
0.1.0
```

NOK: i expect 0.2.0

```shell
GIT_CLIFF__BUMP__INITIAL_TAG=0.2.0 git-cliff --bumped-version
 WARN  git_cliff > "cliff.toml" is not found, using the default configuration.
 WARN  git_cliff_core::release > No releases found, using 0.1.0 as the next version.
0.1.0
```

NOK: i expect v0.2.0

```shell
GIT_CLIFF__BUMP__INITIAL_TAG=v0.2.0 git-cliff --bumped-version
 WARN  git_cliff > "cliff.toml" is not found, using the default configuration.
 WARN  git_cliff_core::release > No releases found, using 0.1.0 as the next version.
0.1.0
```

Project with have tags alreay work perfektly, only new projects are not ok

### Expected behavior

GIT_CLIFF__BUMP__INITIAL_TAG env varialbe should be respected by git-cliff --bumped-version

### Software information

- Operating system: linux
- Rust version: -
- Project version: 2.4.0

**Comment by marsom** [comment]
if I add a cliff.toml in the repository then the varialbe is respected, but not with the default in place

**Comment by orhun** [comment]
#783 potentially fixes this, are you able to test it [locally](https://git-cliff.org/docs/installation/build-from-source)? 😊

**Comment by marsom** [comment]
Im currently on vacation. Ill will test it out when im back

**Comment by orhun** [comment]
Sure, I will merge it then, it will most likely work 👍🏼
