### ISSUE TITLE
Github integration is not run when printing context (`--context`)

### ISSUE THREAD

**Issue by janbuchar** [orhun/git-cliff#780]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

Github integration is not run when printing context, so all the fields added by the integration are empty.

### Steps To Reproduce

1. set up github integration in cliff.toml
2. run `git cliff` 
  - observe a message about fetching release info from github 
3. run `git cliff --context`
  - no message is printed 
  - `*.github` context fields are empty

### Expected behavior

I'd expect the integration to run (and populate the context) in both cases.

### Software information

- Operating system: Arch linux
- Project version: 2.4.0

**Comment by orhun** [comment]
Hey, are you using GitHub related fields (e.g. `github.contributors`) in your `cliff.toml`? GitHub data is not fetched as default as long as it is activated via config.

I tried the following and it worked fine:

```sh
git cliff --context -c github
```

**Comment by janbuchar** [comment]
> Hey, are you using GitHub related fields (e.g. `github.contributors`) in your `cliff.toml`? GitHub data is not fetched as default as long as it is activated via config.

Do I understand it right that I have to use those fields in my templates or else they won't be fetched? Currently I'm using `commit.github.username` and the context (printed with `--context`) looks fine :shrug:

**Comment by orhun** [comment]
Yup, that's correct.

**Comment by janbuchar** [comment]
I see. The line of thought that led me here was that I configured the integration, then I wanted to check if it works by printing out the context and found that it was empty because I haven't touched the templates yet.

Also after https://github.com/orhun/git-cliff/issues/657 is implemented, I believe that users may want to do `git-cliff -x` and then use the github-related context fields in an external filter.

**Comment by orhun** [comment]
I guess we can add another check where if the `remote` is configured we activate the integration also. That will likely solve your case as well since no modification on templates are needed. How does it sound?

**Comment by janbuchar** [comment]
> I guess we can add another check where if the `remote` is configured we activate the integration also. That will likely solve your case as well since no modification on templates are needed. How does it sound?

That sounds perfect!

**Comment by orhun** [comment]
Implemented in #782, any chance that you can check it out [locally](https://git-cliff.org/docs/installation/build-from-source)? 😊
