### ISSUE TITLE
Detailed template errors out with template render error

### ISSUE THREAD

**Issue by adammw** [orhun/git-cliff#785]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

Detailed template config errors out with template render error when running on falcosecurity/falco.

### Steps To Reproduce

1. Install git cliff v2.4.0
2. Clone https://github.com/falcosecurity/falco
3. Run: `git cliff -c detailed`

### Expected behavior

Changelog created without error, or the error to explain why the source data is invalid.

### Screenshots / Logs

```
 git cliff -c detailed --verbose
 INFO  git_cliff > Using built-in configuration file: detailed
 DEBUG git_cliff > No GitHub remote is set, using remote: falco/
 DEBUG git_cliff_core::changelog > Processing the commits...
 DEBUG git_cliff_core::changelog > Processing the releases...
 DEBUG git_cliff_core::changelog > Adding remote data...
 DEBUG git_cliff_core::changelog > Generating changelog...
# Changelog

All notable changes to this project will be documented in this file.

 ERROR git_cliff                 > Template render error:
Filter call 'truncate' failed
Filter `truncate` was called on an incorrect value: got `null` but expected a String
```

### Software information

- Operating system: macOS 14.5 (23F79)
- Rust version: n/a
- Project version: v2.4.0, installed via Homebrew

**Comment by orhun** [comment]
Hey, thanks for reporting! #786 will fix this, you can try it out!

Tip: it seems like you need to set the `tag_pattern` to `[0-9].*` since most of your tags do not have the `v` prefix.
