### ISSUE TITLE
More debug info printed when using -v switch (or -vv?)

### ISSUE THREAD

**Issue by kaushalmodi** [orhun/git-cliff#79]
Hey, I'm glad this issue is resolved by #76, wasn't expecting that 😄 

> @orhun May I suggest that when the user uses `-v` (or may be `-vv`), you print all the environment variables and parsed `git cliff` CLI switch values that affect its output?

Hmm, can you elaborate what you mean with an example? Actually, having a separate issue for tracking this would be great.

_Originally posted by @orhun in https://github.com/orhun/git-cliff/issues/75#issuecomment-1088638663_

---

I meant that when -v or -vv switch is used, `git-cliff` should dump out values of all the environment variables it's going to use, and also the values of all the CLI switches passed by the user.

**Comment by orhun** [comment]
With a8efffc7d57691999583a5a13bfd5d0e48aca095, arguments and parsed configuration is printed to stdout (as trace log) if `-vv` is used. 

I think this should be enough to debug situations like #75, what do you think?

**Comment by kaushalmodi** [comment]
This helps! Thank you.
