### ISSUE TITLE
Allow typical commits to be represented by just the description line

### ISSUE THREAD

**Issue by winksaville** [orhun/git-cliff#81]
**Is your feature request related to a problem? Please describe.**
As stated in the git-cliff `README.md` file a "conventional commit" is:
```
<type>[optional scope]: <description>

[optional body]

[optional footer(s)]
```
Most people, me included, usually create a "typical commit", which looks like this:
```
<description>

[optional body]

[optional footer(s)]
```

**Describe the solution you'd like**
I'd like to be able to "match" on the "typical commit" with something like:
```
{ message = "^.*$", type = "", group = "", body = ".*" }
```
And then handle "typical commits" just as "conventional commits" are handled because the "context" would be the same.

**Describe alternatives you've considered**
I've created [expr-git-diff](https://github.com/winksaville/expr-git-cliff) with [11 typical commits](https://github.com/winksaville/expr-git-cliff/commits/main). Currently the [CHANGELOG.md](https://github.com/winksaville/expr-git-cliff/blob/main/CHANGELOG.md) generated is quite verbose. And because I sometimes use `- some text` in my "typical commit" messages it looks like there are many more than 11 commits. But even if I didn't use `- some text` bodies can be very very large and should not be in CHANGLOG's by default.

**Additional context**
I believe this, [IDEAL_CHANGELOG.md](https://github.com/winksaville/expr-git-cliff/blob/main/IDEAL_CHANGELOG.md), would be a reasonable default for "typical commits".

**Comment by orhun** [comment]
Hello!

You can use the recently added [commit_preprocessors](https://github.com/orhun/git-cliff#commit_preprocessors) feature for this:

```toml
commit_preprocessors = [
    { pattern = "(.*?)\\n.*", replace = "${1}"},
]
```

This will yield:

```
# Changelog

All notable changes to this project will be documented in this file.

## [unreleased]

### Other

- Bump version to v0.3.1
- Change sort_commits to newest
- Bump version to v0.3.0
- An actual CHANGELOG.md
- Add first CHANGELOG.md
- Add cliff.toml
- Bump version to v0.2.0
- Add README.md
- Add licenses
- Change the message of main
- Initial Commit

<!-- generated by git-cliff -->
```

As you can already tell, I can't compare it with your ideal changelog because the tags are missing 🙂 (not pushed to the `expr-git-cliff` repository) But you will get a similar result to your ideal changelog I reckon.

I hope this helps 🐻

**Comment by winksaville** [comment]
Txs!
