### ISSUE TITLE
A line starting with a word and colon in the description of the commit will prevent proper parsing of the body

### ISSUE THREAD

**Issue by mponton-cn** [orhun/git-cliff#82]
**Describe the bug**
A line starting with a word and colon in the description of the commit will prevent proper parsing of the body. For example, a commit showing in `git log` as:

```
fix: something something

First line of the body
IMPORTANT: Please see something else for details.
Another line here.
```

Will have a `body` of `First line of the body` once parsed. Effectively, the word+colon and anything following is interpreted as a footer even if there is no blank line separating it from the body.

**To Reproduce**
1. Setup git/git-cliff for a project
2. Create the commit described above
3. Generate the changelog using a template that includes the commit body (e.g. the one provided below)
4. Body will be mangled in output

**Expected behavior**
The conventional commit doc says:
```
7. A commit body is free-form and MAY consist of any number of newline separated paragraphs.
8. One or more footers MAY be provided one blank line after the body. Each footer MUST consist of a word token, followed by either a <space> or <space># separator, followed by a string value (this is inspired by the [git trailer convention](https://git-scm.com/docs/git-interpret-trailers)).
```
As such I would expect a body that contains a line that starts with a word+colon (including some URL) not to be truncated. Exception maybe for a commit with a body that STARTS with a word+colon since it make determining if this is a body or footer more complicated, or even impossible.

**System (please complete the following information):**
 - git-cliff v0.6.1
 - Windows/Linux (same behavior)

**Additional context**

Sample `cliff.toml`:
```
# configuration file for git-cliff (0.1.0)

[changelog]
# changelog header
header = """
# Changelog\n
All notable changes to this project will be documented in this file.\n
"""
# template for the changelog body
# https://tera.netlify.app/docs/#introduction
body = """
{% if version %}\
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
    ## [unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | upper_first }}
    {% for commit in commits %}
        - {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message | upper_first }}
        ```
        BODY: {{ commit.body }}
        FOOTERS: {{ commit.footers }}
        LINKS: {{ commit.links }}
        ```\
    {% endfor %}
{% endfor %}\n
"""
# remove the leading and trailing whitespace from the template
trim = true
# changelog footer
footer = """
<!-- generated by git-cliff -->
"""

[git]
# parse the commits based on https://www.conventionalcommits.org
conventional_commits = true
# filter out the commits that are not conventional
filter_unconventional = true
# regex for parsing and grouping commits
commit_parsers = [
    { message = "^feat", group = "Features"},
    { message = "^fix", group = "Bug Fixes"},
    { message = "^doc", group = "Documentation"},
    { message = "^perf", group = "Performance"},
    { message = "^refactor", group = "Refactor"},
    { message = "^style", group = "Styling"},
    { message = "^test", group = "Testing"},
    { message = "^chore\\(release\\): prepare for", skip = true},
    { message = "^chore", group = "Miscellaneous Tasks"},
    { body = ".*security", group = "Security"},
]
# filter out the commits that are not matched by commit parsers
filter_commits = false
# glob pattern for matching git tags
tag_pattern = "v[0-9]*"
# regex for skipping tags
skip_tags = "v0.1.0-beta.1"
# regex for ignoring tags
ignore_tags = ""
# sort the tags chronologically
date_order = false
# sort the commits inside sections by oldest/newest order
sort_commits = "oldest"
```

**Comment by orhun** [comment]
Hey!

I submitted an issue to [git-conventional](https://github.com/crate-ci/git-conventional) about this. There isn't much that I can do from `git-cliff`'s side since the parsing is handled by this library.

- https://github.com/crate-ci/git-conventional/issues/24

**Comment by mponton-cn** [comment]
Thanks for doing that! I'll keep in eye on the issue. Considering the situation feel free to close this issue and I can track the one on `git-conventional` if you prefer.

Thanks for sharing this tool, it is much appreciated.

**Comment by orhun** [comment]
New version of `git-conventional` is released with the fix. It is updated in `git-cliff` as well. (f2ccdc366931f29306f99e8ab1cb9389c7710d24)

It will be available with the next release, feel free to try it out and let me know if it works until then! 🐻
