### ISSUE TITLE
Add output file configuration option

### ISSUE THREAD

**Issue by RJSonnenberg** [orhun/git-cliff#827]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

Where I work, it is the common case for us to want to generate and regenerate our CHANGELOG.md docs. Currently, to actually generate a document with git-cliff, we always have to pass it the `--output CHANGELOG.md` argument. This gets tedious to have to type out every time. It also means that, if we happen to typo the file name, we have to rename the file and delete the original (if regenerating).

### Desired solution

Create an `output-file` option that would go under the `[changelog]` section in the `cliff.toml` file that behaves the same as the `--output` CLI argument.

### Alternatives considered

I was not able to discern an alternative solution for this issue.

**Comment by orhun** [comment]
Hey!

It is not implemented in #829 - can you pull from that branch and test it out? 😊 

> [!TIP]
> If you are using `CHANGELOG.md` as default and do not want to give the file name every time, you can simply omit the file name since it is the default.
>
> e.g.
>```sh
> $ git cliff -o
> ```
