### ISSUE TITLE
`--bumped-version` warns if cliff.toml if changelog body is missing

### ISSUE THREAD

**Issue by friday** [orhun/git-cliff#846]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

`git cliff --bumped-version` will warn if cliff.toml is missing, or missing parts. For example: `"cliff.toml" is not found, using the default configuration` or `Changelog body is not specified, using the default template`, even though this command does not use the template.

This is obviously easy to prevent by creating the template, and it doesn't output to stdout, so this is not an urgent issue.

### Steps To Reproduce

git cliff --bumped-version
WARN  git_cliff > "cliff.toml" is not found, using the default configuration.
v1.2.3

### Expected behavior

It should not warn since it doesn't use the template.

### Software information

- Operating system: Arch Linux
- Rust version: -
- Project version: v2.5.0 https://archlinux.org/packages/extra/x86_64/git-cliff/

**Comment by orhun** [comment]
Hello 👋🏼  thanks for reporting!

I'm not sure about suppressing the configuration error, because the bump settings are in fact [configurable](https://git-cliff.org/docs/configuration/bump) so it might be better to let the user know about the absence of a configuration.

What do you think?

> Changelog body is not specified, using the default template

I agree with this though, hence #855 :)

**Comment by friday** [comment]
> I'm not sure about suppressing the configuration error, because the bump settings are in fact [configurable](https://git-cliff.org/docs/configuration/bump) so it might be better to let the user know about the absence of a configuration.

Nice! I just learned about this after creating this issue, but it didn't hit me that it affected the issue :)

> What do you think?

That does makes sense. Although, if you have a `cliff.toml`, but don't specify a [bump] section, then it will not warn right? So I think in some ways it's treated as optional (I assume for backwards compatibility since you recently added it) while in other ways not. Maybe it should be more strict even, as long as you have a reason that's what matters. The warning is useful, after all :+1: 

Thanks for responding so fast, elaborating, and for creating and maintaining this awesome tool :muscle:

**Comment by orhun** [comment]
> if you have a cliff.toml, but don't specify a [bump] section, then it will not warn right?

Yup, correct.

Let me know if you catch any other edge cases where warning seems a bit off or missing and we can probably find a solution to make the user experience better :)

> Thanks for responding so fast, elaborating, and for creating and maintaining this awesome tool 💪

Thanks for the report!
