### ISSUE TITLE
Add support for Jujutsu (when using git store)

### ISSUE THREAD

**Issue by kemitix** [orhun/git-cliff#875]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

Jujutsu is a version control system very similar to Git. It currently uses Git as it's local store. It can work with Git in one of two ways. One is 'co-located', where the `.git` repo is in it's normal location. The other stores the `.git/` files in `.jj/repo/store/git/`. This second is the default when the user clones a Git repo without explicitly requesting that is be co-located.

I would like to be able to use `git-cliff` with a repo that I have checked out locally using the default non-co-located configuration.

### Desired solution

Detecting the alternate location of the `.git/` files should be straight forward. When the `.git/` directory is not found, simply retry using the `.jj/repo/store/git/` directory instead.

Jujutsu is branchless, so there may not be any local branches. There will still be references to the remote branches, e.g. `origin/main`, etc. e.g. `.jj/repo/store/git/refs/remotes/origin/main`.

So, when using the Jujutsu location for the git repo, using the remote branches rather than local ones may be required. (It is possible to have local branches, but this is up to the users discretion/workflow).

### Alternatives considered

Only clone repos with Jujutsu using the co-located option. This is an easy solution with no real downside other than the need to remember to pass the required parameter when cloning.

### Additional context

I recognise that `git-cliff` is aimed at Git compatibility (it's right there in the name!). Jujutsu uses the same on-disk store, so support shouldn't be _too_ difficult to implement. (Then again there's the other 80% of the problem I can't see).

**Comment by orhun** [comment]
Hey, thanks for the suggestion! Jj is actually pretty nice, I maintain it and [`lazyjj`](https://archlinux.org/packages/extra/x86_64/lazyjj/) in the Arch repos.


> When the .git/ directory is not found, simply retry using the .jj/repo/store/git/ directory instead.
> Jujutsu is branchless, so there may not be any local branches. There will still be references to the remote branches

It sounds quite straightforward! Would you be interested in trying that out and seeing if `git-cliff` works as usual? Also, hint: #426 

> Jujutsu uses the same on-disk store, so support shouldn't be too difficult to implement. (Then again there's the other 80% of the problem I can't see).

I think adding support for Jujutsu would be pretty cool, nevertheless!

Something that might come up later is #131 - do you have any idea if `gitoxide` already works well with `jj` repos?

**Comment by kemitix** [comment]
I can certainly give it a go. Let me get my current project squared away and I can look at it then.

I used `gitoxide` a little in `git-next`, but I felt the documentation assumed you already knew the library. It could really do with a "Gitoxide for Git Users" guide (but this is the wrong place for that conversation). I ended up shelling out to `git` for most operations, partly because there are still gaps in the `gitoxide` api that I needed. From what I *was* able to understand, I thing that if it can do what `git-cliff` needs from it with a normal `git` repo, it shouldn't have any problems with a `jj` colocated `git` repo.

**Comment by orhun** [comment]
That sounds great - I also think that implementation would be straightforward, all we need for `git-cliff` to work is retrieving the commits and tags from a repository :)

**Comment by kemitix** [comment]
I've had a look at how the git repo is configured when it is located in `.jj/repo/store/git/`.

* repo is 'bare'
* remote origin is correctly configured
* `HEAD` contains `ref: refs/heads/master`
* the directory `refs/heads/` is empty, i.e. HEAD points to an invalid ref
* the directories `refs/remotes/` and `refs/tags/` are correctly populated

Having `git-cliff` do a simple swap to use `.jj/repo/store/git/` if `.git/` is missing, results in the error:

```
ERROR git_cliff > Git error: `reference 'refs/heads/master' not found; class=Reference (4); code=UnbornBranch (-9)`
```

So, `HEAD` is invalid.

To make the git repo usable we could:

* have the user change `HEAD` manually: `echo "ref: refs/remotes/origin/main" > .jj/repo/store/git/HEAD`
* do the same thing automatically, but selecting `main`, `master`, `trunk` depending on what is available - or allow the user to specify the branch in `cliff.toml`

I would lean towards having the user do it, at least for an initial implementation.

Thoughts @orhun?

**Comment by orhun** [comment]
Thanks for investigating this!

> ref: refs/heads/master

Not related, but it seems like doing `jj clone` on a Git repository assumes that `master` is the main tracking branch. Maybe we should report that to upstream? (if there isn't an issue already)

> echo "ref: refs/remotes/origin/main" > .jj/repo/store/git/HEAD

I'm also wondering if this could be something solved in `jujutsu` itself 🤔
