### ISSUE TITLE
add output from closed issue

### ISSUE THREAD

**Issue by inaryart** [orhun/git-cliff#90]
**Is your feature request related to a problem? Please describe.**
na

**Describe the solution you'd like**
Add output from closed issue, which can be:
1. previous version - current version
1. within a specified period of time
**Describe alternatives you've considered**
na

**Additional context**
Its format is:
```
closed [issue description] (link)
```

**Comment by orhun** [comment]
I didn't quite understand what you're proposing, but there is one thing that is certain which is `git-cliff` is unaware of any Git hosting service. It works with local `git` repositories and it is up to you to customize it to actually add outputs from different sources. For your case, I recommend checking out [link_parsers](https://github.com/orhun/git-cliff#link_parsers) feature to extract certain links (determined by regex) from commit messages.
