### ISSUE TITLE
feat(#1) as conventional commits

### ISSUE THREAD

**Issue by sascha-andres** [orhun/git-cliff#98]
**Is your feature request related to a problem? Please describe.**

I try to create a changelog and have commits like this:

    feat(#1): some message

**Describe the solution you'd like**

I would expect them to show up in Features section, but they do not. If I turn off filter_unconventional then they show up but not changed

How can I make them show up?

**Comment by sascha-andres** [comment]
Tracked that one down to be a feature of git-conventional. So probably nothing to do here

**Comment by orhun** [comment]
Is this still an issue? Have you reported this to git-conventional?

**Comment by sascha-andres** [comment]
Still an issue. And having a `#` inside is not valid for the conventional commit standard. I can open an issue there anyways

**Comment by sascha-andres** [comment]
See issue here: https://github.com/crate-ci/git-conventional/issues/28

**Comment by sascha-andres** [comment]
@orhun git-conventional argues against this
